### ISSUE TITLE
pigmentize + simplegeneric error in python2.7.9

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#1016]
(Original issue 1312 created by None on 2016-12-03T17:04:22.651943+00:00)

On OSX 10.11.6
$ python --version
Python 2.7.9
$ sudo easy_install Pygments
Password:
Searching for Pygments
Reading https://pypi.python.org/simple/Pygments/
Best match: Pygments 2.1.3
Downloading https://pypi.python.org/packages/b8/67/ab177979be1c81bc99c8d0592ef22d547e70bb4c6815c383286ed5dec504/Pygments-2.1.3.tar.gz#md5=ed3fba2467c8afcda4d317e4ef2c6150
Processing Pygments-2.1.3.tar.gz
Writing /tmp/easy_install-cfJ6Qd/Pygments-2.1.3/setup.cfg
Running Pygments-2.1.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-cfJ6Qd/Pygments-2.1.3/egg-dist-tmp-6TpRJw
Adding Pygments 2.1.3 to easy-install.pth file
Installing pygmentize script to /usr/local/bin

Installed /usr/local/lib/python2.7/site-packages/Pygments-2.1.3-py2.7.egg
Processing dependencies for Pygments
Finished processing dependencies for Pygments

$ pygmentize -v -o provi/code.pdf  ~/noMirror/newsemex/E45ws/AnnotatorE4/src/annotator/Activator.java 

*****************************************************************
An unhandled exception occurred while highlighting.
Please report the whole traceback to the issue tracker at
<https://bitbucket.org/birkenfeld/pygments-main/issues>.
*****************************************************************

Traceback (most recent call last):
  File "/usr/local/bin/pygmentize", line 9, in <module>
    load_entry_point('Pygments==2.1.3', 'console_scripts', 'pygmentize')()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Pygments-2.1.3-py2.7.egg/pygments/cmdline.py", line 504, in main
    return main_inner(popts, args, usage)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Pygments-2.1.3-py2.7.egg/pygments/cmdline.py", line 355, in main_inner
    lexer = get_lexer_for_filename(infn, code, **parsed_opts)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Pygments-2.1.3-py2.7.egg/pygments/lexers/__init__.py", line 147, in get_lexer_for_filename
    res = find_lexer_class_for_filename(_fn, code)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Pygments-2.1.3-py2.7.egg/pygments/lexers/__init__.py", line 112, in find_lexer_class_for_filename
    for cls in find_plugin_lexers():
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Pygments-2.1.3-py2.7.egg/pygments/plugin.py", line 53, in find_plugin_lexers
    yield entrypoint.load()
  File "build/bdist.macosx-10.9-x86_64/egg/pkg_resources.py", line 2252, in load
  File "build/bdist.macosx-10.9-x86_64/egg/pkg_resources.py", line 2266, in require
  File "build/bdist.macosx-10.9-x86_64/egg/pkg_resources.py", line 761, in resolve
pkg_resources.VersionConflict: simplegeneric 0.8.1 is installed but simplegeneric>0.8 is required by []

$ sudo easy_install --upgrade simplegeneric
Password:
Searching for simplegeneric
Reading https://pypi.python.org/simple/simplegeneric/
Best match: simplegeneric 0.8.1
Processing simplegeneric-0.8.1-py2.7.egg
simplegeneric 0.8.1 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/site-packages/simplegeneric-0.8.1-py2.7.egg
Processing dependencies for simplegeneric
Finished processing dependencies for simplegeneric

... And the same command pigmentize yields the same error...

**Comment by birkenfeld** [comment]
This is a problem with other installed packages (which are enumerated to find entry-point lexer plugins); pygments itself does not import simplegeneric.
