### ISSUE TITLE
RainbowDashStyle not compatible with Python 2.6

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#1090]
(Original issue 1386 created by None on 2017-10-26T13:22:45.362065+00:00)

Steps to reproduce:
```bash
$ python2.6
>>> from pygments.styles import rainbow_dash
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    from pygments.styles import rainbow_dash
  File "/home/bitstamp.net/damjan.kuznar/workspace/venvs/bitstamp26/lib/python2.6/site-packages/pygments/styles/rainbow_dash.py", line 36, in <module>
    class RainbowDashStyle(Style):
  File "/home/bitstamp.net/damjan.kuznar/workspace/venvs/bitstamp26/lib/python2.6/site-packages/pygments/styles/rainbow_dash.py", line 44, in RainbowDashStyle
    Comment: 'italic {}'.format(BLUE_LIGHT),
ValueError: zero length field name in format
```

**Comment by birkenfeld** [comment]
We're not supporting 2.6 anymore.
