### ISSUE TITLE
unhandled exception occurred while highlighting

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#1109]
(Original issue 1405 created by None on 2017-12-15T20:08:03.175073+00:00)

pygmentize -v -lc sp_solve.c.0 | less -Nr

An unhandled exception occurred while highlighting.

Traceback (most recent call last):
  File "/usr/bin/pygmentize", line 6, in <module>
    sys.exit(pygments.cmdline.main(sys.argv))
  File "/usr/lib/python2.7/dist-packages/pygments/cmdline.py", line 504, in main
    return main_inner(popts, args, usage)
  File "/usr/lib/python2.7/dist-packages/pygments/cmdline.py", line 468, in main_inner
    highlight(code, lexer, fmter, outfile)
  File "/usr/lib/python2.7/dist-packages/pygments/__init__.py", line 87, in highlight
    return format(lex(code, lexer), formatter, outfile)
  File "/usr/lib/python2.7/dist-packages/pygments/__init__.py", line 69, in format
    formatter.format(tokens, outfile)
  File "/usr/lib/python2.7/dist-packages/pygments/formatters/terminal.py", line 101, in format
    return Formatter.format(self, tokensource, outfile)
  File "/usr/lib/python2.7/dist-packages/pygments/formatter.py", line 95, in format
    return self.format_unencoded(tokensource, outfile)
  File "/usr/lib/python2.7/dist-packages/pygments/formatters/terminal.py", line 126, in format_unencoded
    outfile.write(ansiformat(color, line.rstrip('\n')))
  File "/usr/lib/python2.7/codecs.py", line 370, in write
    self.stream.write(data)
IOError: [Errno 32] Broken pipe

**Comment by birkenfeld** [comment]
That's expected if `less` quits.
