### ISSUE TITLE
An unhandled exception occurred while highlighting. pkg_resources.VersionConflict

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#1153]
(Original issue 1449 created by ldavim on 2018-06-21T10:22:48.055489+00:00)

This is the output:

```
*****************************************************************
An unhandled exception occurred while highlighting.
Please report the whole traceback to the issue tracker at
<https://bitbucket.org/birkenfeld/pygments-main/issues>.
*****************************************************************

Traceback (most recent call last):
  File "/usr/local/bin/pygmentize", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/pygments/cmdline.py", line 543, in main
    return main_inner(popts, args, usage)
  File "/usr/local/lib/python3.6/site-packages/pygments/cmdline.py", line 381, in main_inner
    lexer = get_lexer_for_filename(infn, code, **parsed_opts)
  File "/usr/local/lib/python3.6/site-packages/pygments/lexers/__init__.py", line 203, in get_lexer_for_filename
    res = find_lexer_class_for_filename(_fn, code)
  File "/usr/local/lib/python3.6/site-packages/pygments/lexers/__init__.py", line 168, in find_lexer_class_for_filename
    for cls in find_plugin_lexers():
  File "/usr/local/lib/python3.6/site-packages/pygments/plugin.py", line 53, in find_plugin_lexers
    yield entrypoint.load()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2317, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2340, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 779, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (prompt-toolkit 2.0.3 (/usr/local/lib/python3.6/site-packages), Requirement.parse('prompt-toolkit<2.0.0,>=1.0.15'))
```

**Comment by Anteru** [comment]
(Original comment by ldavim on 2018-06-21T10:24:58.195091+00:00)

Trying to update to see if the dependencies are installed with the correct versions doesn't help:
```
$ pip install -U pygments
Requirement already up-to-date: pygments in /usr/local/lib/python3.6/site-packages (2.2.0)
```

**Comment by birkenfeld** [comment]
This is expected when dependencies of installed packages don't work out, since pygments asks `pkg_resources` for plugin lexers. Nothing we can do about it.
