### ISSUE TITLE
invalid syntax when running checksec of pwntools

### ISSUE THREAD

**Issue by shanzhuer** [pygments/pygments#1419]
i got a invalid syntax from pygment2.6.1 when running checksec, i dont know why. there is no problem during installing pwntools.

~/pwn$ checksec stack1
Traceback (most recent call last):
File "/usr/local/bin/checksec", line 11, in
load_entry_point('pwntools==4.2.0.dev0', 'console_scripts', 'checksec')()
File "/usr/local/lib/python2.7/dist-packages/pwntools-4.2.0.dev0-py2.7.egg/pwnlib/commandline/common.py", line 29, in main
import pwnlib.commandline.main
File "/usr/local/lib/python2.7/dist-packages/pwntools-4.2.0.dev0-py2.7.egg/pwnlib/commandline/main.py", line 21, in
from pwnlib.commandline import template
File "/usr/local/lib/python2.7/dist-packages/pwntools-4.2.0.dev0-py2.7.egg/pwnlib/commandline/template.py", line 10, in
from mako.lookup import TemplateLookup
File "/usr/local/lib/python2.7/dist-packages/Mako-1.1.2-py2.7.egg/mako/lookup.py", line 12, in
from mako import exceptions
File "/usr/local/lib/python2.7/dist-packages/Mako-1.1.2-py2.7.egg/mako/exceptions.py", line 305, in
_install_highlighting()
File "/usr/local/lib/python2.7/dist-packages/Mako-1.1.2-py2.7.egg/mako/exceptions.py", line 300, in _install_highlighting
_install_pygments()
File "/usr/local/lib/python2.7/dist-packages/Mako-1.1.2-py2.7.egg/mako/exceptions.py", line 284, in _install_pygments
from mako.ext.pygmentplugin import syntax_highlight # noqa
File "/usr/local/lib/python2.7/dist-packages/Mako-1.1.2-py2.7.egg/mako/ext/pygmentplugin.py", line 8, in
from pygments.formatters.html import HtmlFormatter
File "/usr/local/lib/python2.7/dist-packages/Pygments-2.6.1-py2.7.egg/pygments/formatters/html.py", line 554
file=sys.stderr)
^
SyntaxError: invalid syntax

**Comment by birkenfeld** [comment]
Pygments 2.6 has dropped support for Python 2.
