### ISSUE TITLE
Unhandled Exception in Windows while using less.exe

### ISSUE THREAD

**Issue by frossm** [pygments/pygments#1420]
Hello pygment folks,

Just started to use pygmentize on windows as I'm looking to get less.exe to have syntax highlighting.  Works great.  However, if I pipe the results to less and then hit 'q' to exit less, I get the following issue.

`pygmentize -v fin.scm | less`

(the code is displayed colorized...I then hit q to exit)

```
*****************************************************************
An unhandled exception occurred while highlighting.
Please report the whole traceback to the issue tracker at
<https://github.com/pygments/pygments/issues>.
*****************************************************************

Traceback (most recent call last):
  File "c:\apps\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\apps\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Apps\Python\Scripts\pygmentize.exe\__main__.py", line 7, in <module>
  File "c:\apps\python\lib\site-packages\pygments\cmdline.py", line 550, in main
    return main_inner(popts, args, usage)
  File "c:\apps\python\lib\site-packages\pygments\cmdline.py", line 518, in main_inner
    highlight(code, lexer, fmter, outfile)
  File "c:\apps\python\lib\site-packages\pygments\__init__.py", line 84, in highlight
    return format(lex(code, lexer), formatter, outfile)
  File "c:\apps\python\lib\site-packages\pygments\__init__.py", line 66, in format
    formatter.format(tokens, outfile)
  File "c:\apps\python\lib\site-packages\pygments\formatters\terminal.py", line 95, in format
    return Formatter.format(self, tokensource, outfile)
  File "c:\apps\python\lib\site-packages\pygments\formatter.py", line 95, in format
    return self.format_unencoded(tokensource, outfile)
  File "c:\apps\python\lib\site-packages\pygments\formatters\terminal.py", line 120, in format_unencoded
    outfile.write(ansiformat(color, line.rstrip('\n')))
BrokenPipeError: [Errno 32] Broken pipe
```

This looks a bit different than [#1109](https://github.com/pygments/pygments/issues/1109) and [#1153](https://github.com/pygments/pygments/issues/1153) although it may be the same root issue.

Certainly not a critical issue as it's just an error message at the end, but I wanted to ensure it was reported and I do hope it's a simple fix.

Thanks for the time to look at this and the great program.

Michael

**Comment by birkenfeld** [comment]
Thanks for the report; this is exactly #1109, however I think now that the SIGPIPE exception should be handled better.

**Comment by bhrutledge** [comment]
I'm experiencing this on macOS as well. I found this with some suggested fixes:

https://stackoverflow.com/questions/14207708/ioerror-errno-32-broken-pipe-python
