### ISSUE TITLE
Incorrect Java file lexer guess

### ISSUE THREAD

**Issue by pombredanne** [pygments/pygments#1563]
With the attached file (to rename to a `.JAVA` UPPERCASE extension) the lexer is guessed incorrectly as Python.
See [Logger.JAVA.txt](https://github.com/pygments/pygments/files/5322951/Logger.JAVA.txt)
When the extension is lowercased to '.jav`, the lexer is guessed OK from the filename.
In all cases, the content-based guess is not correct

```
$ python
Python 3.6.10 (default, Jun 13 2020, 08:53:46) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygments
>>> pygments.__version__
'2.7.1'
>>> from pygments import lexers 
>>> fn='Logger.JAVA'
>>> code=open(f).read()
>>> lexers.get_lexer_for_filename(fn, code)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/lib/python3.6/site-packages/pygments/lexers/__init__.py", line 210, in get_lexer_for_filename
    raise ClassNotFound('no lexer for filename %r found' % _fn)
pygments.util.ClassNotFound: no lexer for filename 'Logger.JAVA' found
>>> lexers.guess_lexer(code)
<pygments.lexers.Python2Lexer>
>>> fn='Logger.java'
>>> lexers.get_lexer_for_filename(fn, code)
<pygments.lexers.JavaLexer>
```

**Comment by pombredanne** [comment]
I am not sure there is an easy fix because: 
- the filenames resolves to globs which are case-sensitive https://github.com/pygments/pygments/blob/91728aedb249ecce18b7077f6e94875b8204a7e5/pygments/lexers/jvm.py#L34
- some lexers care for the case of the these filenames
... therefore testing for filenames for in a case-insensitive way may not be correct at all times but that may be minor.

One weird outcome is that with the exact same file and file name a lexer may be reported based on a filename on Windows (case-normalized fnmatch) and not on Linux.
