### ISSUE TITLE
PowerShell syntax highlighting

### ISSUE THREAD

**Issue by Sherlock221B** [pygments/pygments#1580]
I need to highlight some powershell code and I discovered a strange behavior.
If I use the code below everything is working fine :
```
echo '$titi=coucou' | pygmentize -l powershell -F raiseonerror
$titi=coucou
```

But if i use the code below i get an error :
```
PS C:\Users\SM> echo 'PS C:\Users\SM>  $titi="tutu"' | pygmentize -l powershell -F raiseonerror -v
PS C
*****************************************************************
An unhandled exception occurred while highlighting.
Please report the whole traceback to the issue tracker at
<https://github.com/pygments/pygments/issues>.
*****************************************************************

Traceback (most recent call last):
  File "c:\program files (x86)\python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files (x86)\python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Python38-32\Scripts\pygmentize.exe\__main__.py", line 7, in <module>
  File "c:\program files (x86)\python38-32\lib\site-packages\pygments\cmdline.py", line 557, in main
    return main_inner(popts, args, usage)
  File "c:\program files (x86)\python38-32\lib\site-packages\pygments\cmdline.py", line 519, in main_inner
    highlight(code, lexer, fmter, outfile)
  File "c:\program files (x86)\python38-32\lib\site-packages\pygments\__init__.py", line 84, in highlight
    return format(lex(code, lexer), formatter, outfile)
  File "c:\program files (x86)\python38-32\lib\site-packages\pygments\__init__.py", line 66, in format
    formatter.format(tokens, outfile)
  File "c:\program files (x86)\python38-32\lib\site-packages\pygments\formatters\terminal.py", line 95, in format
    return Formatter.format(self, tokensource, outfile)
  File "c:\program files (x86)\python38-32\lib\site-packages\pygments\formatter.py", line 95, in format
    return self.format_unencoded(tokensource, outfile)
  File "c:\program files (x86)\python38-32\lib\site-packages\pygments\formatters\terminal.py", line 115, in format_unencoded
    for ttype, value in tokensource:
  File "c:\program files (x86)\python38-32\lib\site-packages\pygments\filter.py", line 20, in _apply
    yield from filter_.filter(lexer, stream)
  File "c:\program files (x86)\python38-32\lib\site-packages\pygments\filters\__init__.py", line 783, in filter
    raise self.exception(value)
pygments.filters.ErrorToken: :
```

Even stranger, if I run the following command I don't have an error
```
echo 'PS C::\Users\SM>  $titi="tutu"' | pygmentize -l powershell -F raiseonerror
PS C::\Users\SM>  $titi="tutu"
```

Please note, I am working under Windows, I did not have time to do the same test under Linux.

Best regards.

**Comment by Sherlock221B** [comment]
I read the source code and found the solution, I was using the wrong lexer, instead of powershell I have to use ps1con because it is a PowerShell session.
Sorry for the inconvenience.

**Comment by Anteru** [comment]
No worries, glad you got it sorted out!
