### ISSUE TITLE
PowerShell ErrorToken: :

### ISSUE THREAD

**Issue by jborean93** [pygments/pygments#1682]
Running `Pygments==2.7.4` I'm having issues highlighting PowerShell syntax.

It seems like the PowerShell syntax highlighter is failing when it encounters `:` in the code. A very simple example

```bash
echo '$item = Get-ChildItem C:\temp' | pygmentize -l powershell -F raiseonerror -v
```

Outputs the following

```
*****************************************************************
An unhandled exception occurred while highlighting.
Please report the whole traceback to the issue tracker at
<https://github.com/pygments/pygments/issues>.
*****************************************************************

$item = Get-ChildItem CTraceback (most recent call last):
  File "/home/jborean/venvs/psrp-39/bin/pygmentize", line 8, in <module>
    sys.exit(main())
  File "/home/jborean/venvs/psrp-39/lib/python3.9/site-packages/pygments/cmdline.py", line 557, in main
    return main_inner(popts, args, usage)
  File "/home/jborean/venvs/psrp-39/lib/python3.9/site-packages/pygments/cmdline.py", line 519, in main_inner
    highlight(code, lexer, fmter, outfile)
  File "/home/jborean/venvs/psrp-39/lib/python3.9/site-packages/pygments/__init__.py", line 84, in highlight
    return format(lex(code, lexer), formatter, outfile)
  File "/home/jborean/venvs/psrp-39/lib/python3.9/site-packages/pygments/__init__.py", line 66, in format
    formatter.format(tokens, outfile)
  File "/home/jborean/venvs/psrp-39/lib/python3.9/site-packages/pygments/formatters/terminal.py", line 95, in format
    return Formatter.format(self, tokensource, outfile)
  File "/home/jborean/venvs/psrp-39/lib/python3.9/site-packages/pygments/formatter.py", line 95, in format
    return self.format_unencoded(tokensource, outfile)
  File "/home/jborean/venvs/psrp-39/lib/python3.9/site-packages/pygments/formatters/terminal.py", line 115, in format_unencoded
    for ttype, value in tokensource:
  File "/home/jborean/venvs/psrp-39/lib/python3.9/site-packages/pygments/filter.py", line 20, in _apply
    yield from filter_.filter(lexer, stream)
  File "/home/jborean/venvs/psrp-39/lib/python3.9/site-packages/pygments/filters/__init__.py", line 783, in filter
    raise self.exception(value)
pygments.filters.ErrorToken: :
```

Doing just `C\temp` works just fine but that's not the code I want to be demonstrating. A colon is used quite a bit in PowerShell so I'm hoping I just have some config option set incorrectly.

**Comment by jborean93** [comment]
Looks like quoting the string containing the `:` will work e.g. `"C:\temp"` or `'C:\temp'` so I have a workaround but it would be nice to not have to do so.

It seems like `$<scope>:var` works without quoting as per https://github.com/pygments/pygments/blob/a590ac5ea7c00a41e253834306bfa19e38349c0b/pygments/lexers/shell.py#L729 but there are a few other cases I can think off just off the top of my head which does not work currently.

```powershell
# As mentioned above, using a PSProvider path qualifier, e.g. 'C:', 'cert:', 'wsman:' (can be any user defined prefix

# Using ${} when getting a var with path qualifier or special chars, e.g. '${function:Test-Path}'
Invoke-Command computer -ScriptBlock ${function:Test-Path}
```

I'm just getting started with pygments and PowerShell so I might come across some more. What's the best way to report these issues?

**Comment by Anteru** [comment]
Keep them coming here, ideally with an associated pull request :) There have been a few people looking into Powershell recently so hopefully someone can pick this up.

**Comment by jborean93** [comment]
Thanks, I might play around with it a bit more and see what I can do. Regex isn't my thing but hopefully I can still help a bit.

**Comment by Anteru** [comment]
Thanks! It's hopefully possible to reuse some of the DOS/cmd shell rules for this.
