### ISSUE TITLE
Python 3.9 removed `gcd` from `fractions`, causing ImportError

### ISSUE THREAD

**Issue by Paul-Aime** [pygments/pygments#1777]
As the title says, I get an `ImportError: cannot import name 'gcd' from 'fractions'`, when using command-line interface.

From python documentation, it is "[Deprecated since version 3.5: Use `math.gcd()` instead.](https://docs.python.org/3.8/library/fractions.html#fractions.gcd)".

## Environments

It is on Ubuntu 20.04, in a conda environement:

```bash
$ conda list pygments
# packages in environment at /home/p20aime/anaconda3/envs/sos:
#
# Name                    Version                   Build  Channel
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
pygments                  2.8.1              pyhd8ed1ab_0    conda-forge

$ which pygmentize
/home/p20aime/anaconda3/envs/sos/bin/pygmentize

$ pygmentize -V
Pygments version 2.8.1, (c) 2006-2021 by Georg Brandl, Matthäus Chajdas and contributors.

$ python -V
Python 3.9.4
```

I have another conda environment with python3.9 + pygments 2.8.0 installed and I don't have this issue.

## Traceback

```python
$ pygmentize -gv /home/p20aime/.local/share/jupyter/kernels/jmatlab/kernel.json

Traceback (most recent call last):
  File "/home/p20aime/anaconda3/envs/sos/bin/pygmentize", line 10, in <module>
    sys.exit(main())
  File "/home/p20aime/anaconda3/envs/sos/lib/python3.9/site-packages/pygments/cmdline.py", line 577, in main
    return main_inner(parser, argns)
  File "/home/p20aime/anaconda3/envs/sos/lib/python3.9/site-packages/pygments/cmdline.py", line 305, in main_inner
    lexer = get_lexer_for_filename(infn, code, **parsed_opts)
  File "/home/p20aime/anaconda3/envs/sos/lib/python3.9/site-packages/pygments/lexers/__init__.py", line 207, in get_lexer_for_filename
    res = find_lexer_class_for_filename(_fn, code)
  File "/home/p20aime/anaconda3/envs/sos/lib/python3.9/site-packages/pygments/lexers/__init__.py", line 172, in find_lexer_class_for_filename
    for cls in find_plugin_lexers():
  File "/home/p20aime/anaconda3/envs/sos/lib/python3.9/site-packages/pygments/plugin.py", line 54, in find_plugin_lexers
    yield entrypoint.load()
  File "/home/p20aime/anaconda3/envs/sos/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/home/p20aime/anaconda3/envs/sos/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/p20aime/anaconda3/envs/sos/lib/python3.9/site-packages/sos/__init__.py", line 12, in <module>
    from .workflow_executor import Base_Executor
  File "/home/p20aime/anaconda3/envs/sos/lib/python3.9/site-packages/sos/workflow_executor.py", line 21, in <module>
    from .dag import SoS_DAG
  File "/home/p20aime/anaconda3/envs/sos/lib/python3.9/site-packages/sos/dag.py", line 11, in <module>
    import networkx as nx
  File "/home/p20aime/anaconda3/envs/sos/lib/python3.9/site-packages/networkx/__init__.py", line 114, in <module>
    import networkx.generators
  File "/home/p20aime/anaconda3/envs/sos/lib/python3.9/site-packages/networkx/generators/__init__.py", line 14, in <module>
    from networkx.generators.intersection import *
  File "/home/p20aime/anaconda3/envs/sos/lib/python3.9/site-packages/networkx/generators/intersection.py", line 13, in <module>
    from networkx.algorithms import bipartite
  File "/home/p20aime/anaconda3/envs/sos/lib/python3.9/site-packages/networkx/algorithms/__init__.py", line 16, in <module>
    from networkx.algorithms.dag import *
  File "/home/p20aime/anaconda3/envs/sos/lib/python3.9/site-packages/networkx/algorithms/dag.py", line 23, in <module>
    from fractions import gcd
ImportError: cannot import name 'gcd' from 'fractions' (/home/p20aime/anaconda3/envs/sos/lib/python3.9/fractions.py)
```

**Comment by Paul-Aime** [comment]
Sorry, this has nothing to do with `pygments`... closing it now.

**Comment by Anteru** [comment]
I was just about to write this :) The callstack points somewhere else
