### ISSUE TITLE
dts/devicetree lexer doesn't like `qcom,rpm-rbcpr-stats@0x200000 {`

### ISSUE THREAD

**Issue by Robpol86** [pygments/pygments#1949]
The following snippet generated by `dtc -I fs -O dts /proc/device-tree` fails:

```
/dts-v1/;

/ {
	#size-cells = < 0x01 >;
	qcom,msm-id = < 0x122 0x10000 0x128 0x10000 0x129 0x10000 0x12a 0x10000 0x12b 0x10000 >;
	compatible = "qcom,mdm9607-mtp\0qcom,mdm9607\0qcom,mtp";
	#address-cells = < 0x01 >;
	model = "Franklin Technologies, Inc. MDM 9607 R717 P1";
	qcom,board-id = < 0x1a 0x00 >;
	interrupt-parent = < 0x01 >;

	soc {
		#size-cells = < 0x01 >;
		#address-cells = < 0x01 >;
		ranges;

		qcom,rpm-rbcpr-stats@0x200000 {
			compatible = "qcom,rpmrbcpr-stats";
			reg = < 0x200000 0x1000 >;
			qcom,start-offset = < 0x90010 >;
		};
	};
};
```

```
[10T11:53:18] Moops10:robpol86.com venv:(.venv) git:(franklin*) $ pygmentize -V
Pygments version 2.10.0, (c) 2006-2021 by Georg Brandl, Matthäus Chajdas and contributors.
[10T11:53:20] Moops10:robpol86.com venv:(.venv) git:(franklin*) $ python3 -V
Python 3.7.3
[10T11:53:25] Moops10:robpol86.com venv:(.venv) git:(franklin*) $ pygmentize -vF raiseonerror -l dts docs/_static/t9_device_tree.dts
/dts-v1/;

/ {
        #size-cells = < 0x01 >;
        qcom,msm-id = < 0x122 0x10000 0x128 0x10000 0x129 0x10000 0x12a 0x10000 0x12b 0x10000 >;
        compatible = "qcom,mdm9607-mtp\0qcom,mdm9607\0qcom,mtp";
        #address-cells = < 0x01 >;
        model = "Franklin Technologies, Inc. MDM 9607 R717 P1";
        qcom,board-id = < 0x1a
*****************************************************************
An unhandled exception occurred while highlighting.
Please report the whole traceback to the issue tracker at
<https://github.com/pygments/pygments/issues>.
*****************************************************************

0x00 >;
        interrupt-parent = < 0x01 >;

        soc {
                #size-cells = < 0x01 >;
                #address-cells = < 0x01 >;
                ranges;

                qcom,rpm-rbcpr-statsTraceback (most recent call last):
  File "/home/robpol86/workspace/robpol86.com/.venv/bin/pygmentize", line 8, in <module>
    sys.exit(main())
  File "/home/robpol86/workspace/robpol86.com/.venv/lib/python3.7/site-packages/pygments/cmdline.py", line 577, in main
    return main_inner(parser, argns)
  File "/home/robpol86/workspace/robpol86.com/.venv/lib/python3.7/site-packages/pygments/cmdline.py", line 433, in main_inner
    highlight(code, lexer, fmter, outfile)
  File "/home/robpol86/workspace/robpol86.com/.venv/lib/python3.7/site-packages/pygments/__init__.py", line 83, in highlight
    return format(lex(code, lexer), formatter, outfile)
  File "/home/robpol86/workspace/robpol86.com/.venv/lib/python3.7/site-packages/pygments/__init__.py", line 65, in format
    formatter.format(tokens, outfile)
  File "/home/robpol86/workspace/robpol86.com/.venv/lib/python3.7/site-packages/pygments/formatters/terminal256.py", line 252, in format
    return Formatter.format(self, tokensource, outfile)
  File "/home/robpol86/workspace/robpol86.com/.venv/lib/python3.7/site-packages/pygments/formatter.py", line 94, in format
    return self.format_unencoded(tokensource, outfile)
  File "/home/robpol86/workspace/robpol86.com/.venv/lib/python3.7/site-packages/pygments/formatters/terminal256.py", line 258, in format_unencoded
    for ttype, value in tokensource:
  File "/home/robpol86/workspace/robpol86.com/.venv/lib/python3.7/site-packages/pygments/filter.py", line 19, in _apply
    yield from filter_.filter(lexer, stream)
  File "/home/robpol86/workspace/robpol86.com/.venv/lib/python3.7/site-packages/pygments/filters/__init__.py", line 782, in filter
    raise self.exception(value)
pygments.filters.ErrorToken: @
```

If I replace `qcom,rpm-rbcpr-stats@0x200000` with either `qcom,rpm-rbcpr-stats@0200000` or `qcom,rpm-rbcpr-stats0x200000` it works fine.

**Comment by birkenfeld** [comment]
Thanks for the report!
