### ISSUE TITLE
Pygmentize does not find my own style

### ISSUE THREAD

**Issue by qoheniac** [pygments/pygments#1976]
If I write a custom style I can use it from within `python` but not from the command line interface `pygmentize`. Here is a minimal (not) working example:

### Install style

**setup.py**
```python
from setuptools import setup

setup(
    name="mystyle",
    install_requires=["pygments"],
    packages=["mystyle"],
    entry_points="""
    [pygments.styles]
    mystyle = mystyle:MyStyle
    """,
)
```

**mystyle/__init__.py**
```python
from pygments.style import Style
from pygments.token import Keyword, String


class MyStyle(Style):
    styles = {
        Keyword: "#0000FF",
        String: "#FF0000",
    }
```
I install it by running `pip install --user .`

### Test style

I can successfully test that style for example by using a test script like this:

**test.py**
```python
from pygments import highlight
from pygments.formatters import Terminal256Formatter
from pygments.styles import get_style_by_name
from pygments.lexers import get_lexer_by_name

with open("test.py") as f:
    print(
        highlight(
            f.read(),
            get_lexer_by_name("python"),
            Terminal256Formatter(style=get_style_by_name("mystyle")),
        )
    )
```

While running `python test.py` works perfectly fine, `pygmentize -vO style=mystyle test.py` crashes with the following traceback:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pygments/styles/__init__.py", line 74, in get_style_by_name
    mod = __import__('pygments.styles.' + mod, None, None, [cls])
ModuleNotFoundError: No module named 'pygments.styles.mystyle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pygmentize", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/pygments/cmdline.py", line 577, in main
    return main_inner(parser, argns)
  File "/usr/lib/python3.10/site-packages/pygments/cmdline.py", line 392, in main_inner
    fmter = Terminal256Formatter(**parsed_opts)
  File "/usr/lib/python3.10/site-packages/pygments/formatters/terminal256.py", line 138, in __init__
    Formatter.__init__(self, **options)
  File "/usr/lib/python3.10/site-packages/pygments/formatter.py", line 66, in __init__
    self.style = _lookup_style(options.get('style', 'default'))
  File "/usr/lib/python3.10/site-packages/pygments/formatter.py", line 21, in _lookup_style
    return get_style_by_name(style)
  File "/usr/lib/python3.10/site-packages/pygments/styles/__init__.py", line 76, in get_style_by_name
    raise ClassNotFound("Could not find style module %r" % mod +
pygments.util.ClassNotFound: Could not find style module 'mystyle'.
```

###  Install style differently

If I install the style without `pip` by just linking the style definition like this

```
sudo ln -s /path/to/__init__.py /usr/lib/python3.10/site-packages/pygments/styles/mystyle.py
```

and changing the class name from `MyStyle` to `MystyleStyle` I get the same behavior as before, i. e. running `python test.py` works fine while `pygmentize` doesn't.

### System information

- Fedora 35
- Python 3.10.0
- Pygments 2.9.0

**Comment by qoheniac** [comment]
Never mind, I just tried Pygments 2.10.0 (installed via `pip install -U --user pygments`) and the issue is gone. So this is either a problem with Pygments 2.9.0 or with the way Fedora ships it.
