### ISSUE TITLE
AttributeError on pygments.plugin::iter_entry_points 

### ISSUE THREAD

**Issue by rachmadaniHaryono** [pygments/pygments#1977]
### Subject of the issue

pygments error when running with ptipython and poetry

### Your environment

- poetry 1.1.12
- ptipython 3.0.20
- os: ubuntu 21.10
- pygments : 2.10.0

<details><summary>console</summary>
<p>

```console
> pipx --version
0.16.4
> pipx runpip ptpython freeze
appdirs==1.4.4
backcall==0.2.0
decorator==5.1.0
ipython==7.29.0
jedi==0.18.0
matplotlib-inline==0.1.3
parso==0.8.2
pexpect==4.8.0
pickleshare==0.7.5
prompt-toolkit==3.0.22
ptpython==3.0.20
ptyprocess==0.7.0
Pygments==2.10.0
traitlets==5.1.1
wcwidth==0.2.5
> pipx runpip poetry freeze
backports.entry-points-selectable==1.1.1
CacheControl==0.12.10
cachy==0.3.0
certifi==2021.10.8
cffi==1.15.0
charset-normalizer==2.0.8
cleo==0.8.1
clikit==0.6.2
crashtest==0.3.1
cryptography==36.0.0
distlib==0.3.3
filelock==3.4.0
html5lib==1.1
idna==3.3
jeepney==0.7.1
keyring==21.8.0
lockfile==0.12.2
msgpack==1.0.3
packaging==20.9
pastel==0.2.1
pexpect==4.8.0
pkginfo==1.8.1
platformdirs==2.4.0
poetry==1.1.12
poetry-core==1.0.7
ptyprocess==0.7.0
pycparser==2.21
pylev==1.4.0
pyparsing==3.0.6
requests==2.26.0
requests-toolbelt==0.9.1
SecretStorage==3.3.1
shellingham==1.4.0
six==1.16.0
tomlkit==0.7.2
urllib3==1.26.7
virtualenv==20.10.0
webencodings==0.5.1
> pipx list --include-injected
venvs are in /home/r3r/.local/pipx/venvs
apps are exposed on your $PATH at /home/r3r/.local/bin
   package poetry 1.1.12, Python 3.10.0
    - poetry
   package ptpython 3.0.20, Python 3.10.0
    - ptipython
    - ptipython3
    - ptipython3.9
    - ptpython
    - ptpython3
    - ptpython3.9
    Injected Packages:
      - ipython 7.29.0
```
</p>
</details>

### Steps to reproduce
1. install pipx, poetry with pipx and ptpython with ipython
1. `poetry new temp2`
2. `cd temp2`
3. `poetry run ptipython`

### Expected behaviour
ptipython run succefully 

or 

no error from pygments

### Actual behaviour

```python
~/.local/pipx/venvs/ptpython/lib/python3.10/site-packages/pygments/styles/__init__.py in get_all_styles()
     86     both builtin and plugin."""
     87     yield from STYLE_MAP
---> 88     for name, _ in find_plugin_styles():
     89         yield name

~/.local/pipx/venvs/ptpython/lib/python3.10/site-packages/pygments/plugin.py in find_plugin_styles()
     61
     62 def find_plugin_styles():
---> 63     for entrypoint in iter_entry_points(STYLE_ENTRY_POINT):
     64         yield entrypoint.name, entrypoint.load()
     65

~/.local/pipx/venvs/ptpython/lib/python3.10/site-packages/pygments/plugin.py in iter_entry_points(group_name)
     43 def iter_entry_points(group_name):
     44     try:
---> 45         import pkg_resources
     46     except (ImportError, OSError):
     47         return []

~/.local/pipx/shared/lib/python3.10/site-packages/pkg_resources/__init__.py in <module>
   3264
   3265 @_call_aside
-> 3266 def _initialize_master_working_set():
   3267     """
   3268     Prepare the master working set and make the ``require()``

~/.local/pipx/shared/lib/python3.10/site-packages/pkg_resources/__init__.py in _call_aside(f, *args, **kwargs)
   3238 # from jaraco.functools 1.3
   3239 def _call_aside(f, *args, **kwargs):
-> 3240     f(*args, **kwargs)
   3241     return f
   3242

~/.local/pipx/shared/lib/python3.10/site-packages/pkg_resources/__init__.py in _initialize_master_working_set()
   3276     at their own risk.
   3277     """
-> 3278     working_set = WorkingSet._build_master()
   3279     _declare_state('object', working_set=working_set)
   3280

~/.local/pipx/shared/lib/python3.10/site-packages/pkg_resources/__init__.py in _build_master(cls)
    562         Prepare the master working set.
    563         """
--> 564         ws = cls()
    565         try:
    566             from __main__ import __requires__

~/.local/pipx/shared/lib/python3.10/site-packages/pkg_resources/__init__.py in __init__(self, entries)
    555
    556         for entry in entries:
--> 557             self.add_entry(entry)
    558
    559     @classmethod

~/.local/pipx/shared/lib/python3.10/site-packages/pkg_resources/__init__.py in add_entry(self, entry)
    611         self.entry_keys.setdefault(entry, [])
    612         self.entries.append(entry)
--> 613         for dist in find_distributions(entry, True):
    614             self.add(dist, entry, False)
    615

~/.local/pipx/shared/lib/python3.10/site-packages/pkg_resources/__init__.py in find_distributions(path_item, only)
   1967 def find_distributions(path_item, only=False):
   1968     """Yield distributions accessible via `path_item`"""
-> 1969     importer = get_importer(path_item)
   1970     finder = _find_adapter(_distribution_finders, importer)
   1971     return finder(importer, path_item, only)

~/.pyenv/versions/3.10.0/lib/python3.10/pkgutil.py in get_importer(path_item)
    419         for path_hook in sys.path_hooks:
    420             try:
--> 421                 importer = path_hook(path_item)
    422                 sys.path_importer_cache.setdefault(path_item, importer)
    423                 break

~/.pyenv/versions/3.10.0/lib/python3.10/importlib/_bootstrap_external.py in path_hook_for_FileFinder(path)

~/.pyenv/versions/3.10.0/lib/python3.10/importlib/_bootstrap_external.py in __init__(self, path, *loader_details)

~/.pyenv/versions/3.10.0/lib/python3.10/importlib/_bootstrap_external.py in _path_isabs(path)

AttributeError: 'PosixPath' object has no attribute 'startswith'

```

<details><summary>full error</summary>
<p>

```python
> poetry run ptipython
Creating virtualenv temp2-Yh2U4OzJ-py3.10 in /home/r3r/.cache/pypoetry/virtualenvs
/home/r3r/.local/pipx/venvs/ptpython/lib/python3.10/site-packages/IPython/core/interactiveshell.py:934: UserWarning: Attempting to work in a virtualenv. If you encounter problems, please install IPython inside the virtualenv.
  warn("Attempting to work in a virtualenv. If you encounter problems, please "
Error processing line 1 of /home/r3r/.cache/pypoetry/virtualenvs/temp2-Yh2U4OzJ-py3.10/lib/python3.10/site-packages/_virtualenv.pth:

  Traceback (most recent call last):
    File "/home/r3r/.pyenv/versions/3.10.0/lib/python3.10/site.py", line 186, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_virtualenv'

Remainder of file ignored
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/.pyenv/versions/3.10.0/lib/python3.10/pkgutil.py in get_importer(path_item)
    416     try:
--> 417         importer = sys.path_importer_cache[path_item]
    418     except KeyError:

KeyError: PosixPath('/home/r3r/.cache/pypoetry/virtualenvs/temp2-Yh2U4OzJ-py3.10/lib/python3.10/site-packages')

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
~/.local/bin/ptipython in <module>
      6 if __name__ == '__main__':
      7     sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
----> 8     sys.exit(run())

~/.local/pipx/venvs/ptpython/lib/python3.10/site-packages/ptpython/entry_points/run_ptipython.py in run(user_ns)
     68
     69         # Run interactive shell.
---> 70         embed(
     71             vi_mode=a.vi,
     72             history_filename=history_file,

~/.local/pipx/venvs/ptpython/lib/python3.10/site-packages/ptpython/ipython.py in embed(**kwargs)
    281         config.InteractiveShellEmbed = config.TerminalInteractiveShell
    282         kwargs["config"] = config
--> 283     shell = InteractiveShellEmbed.instance(**kwargs)
    284     initialize_extensions(shell, config["InteractiveShellApp"]["extensions"])
    285     run_startup_scripts(shell)

~/.local/pipx/venvs/ptpython/lib/python3.10/site-packages/traitlets/config/configurable.py in instance(cls, *args, **kwargs)
    538         # Create and save the instance
    539         if cls._instance is None:
--> 540             inst = cls(*args, **kwargs)
    541             # Now make sure that the instance will also be returned by
    542             # parent classes' _instance attribute.

~/.local/pipx/venvs/ptpython/lib/python3.10/site-packages/ptpython/ipython.py in __init__(self, *a, **kw)
    225             return self.user_ns
    226
--> 227         python_input = IPythonInput(
    228             self,
    229             get_globals=get_globals,

~/.local/pipx/venvs/ptpython/lib/python3.10/site-packages/ptpython/ipython.py in __init__(self, ipython_shell, *a, **kw)
    181         kw["_validator"] = IPythonValidator(get_compiler_flags=self.get_compiler_flags)
    182
--> 183         super().__init__(*a, **kw)
    184         self.ipython_shell = ipython_shell
    185

~/.local/pipx/venvs/ptpython/lib/python3.10/site-packages/ptpython/python_input.py in __init__(self, get_globals, get_locals, history_filename, vi_mode, color_depth, input, output, extra_key_bindings, create_app, _completer, _validator, _lexer, _extra_buffer_processors, _extra_layout_body, _extra_toolbars, _input_buffer_height)
    328
    329         #: Load styles.
--> 330         self.code_styles: Dict[str, BaseStyle] = get_all_code_styles()
    331         self.ui_styles = get_all_ui_styles()
    332         self._current_code_style_name: str = "default"

~/.local/pipx/venvs/ptpython/lib/python3.10/site-packages/ptpython/style.py in get_all_code_styles()
     13     Return a mapping from style names to their classes.
     14     """
---> 15     result: Dict[str, BaseStyle] = {
     16         name: style_from_pygments_cls(get_style_by_name(name))
     17         for name in get_all_styles()

~/.local/pipx/venvs/ptpython/lib/python3.10/site-packages/ptpython/style.py in <dictcomp>(.0)
     13     Return a mapping from style names to their classes.
     14     """
---> 15     result: Dict[str, BaseStyle] = {
     16         name: style_from_pygments_cls(get_style_by_name(name))
     17         for name in get_all_styles()

~/.local/pipx/venvs/ptpython/lib/python3.10/site-packages/pygments/styles/__init__.py in get_all_styles()
     86     both builtin and plugin."""
     87     yield from STYLE_MAP
---> 88     for name, _ in find_plugin_styles():
     89         yield name

~/.local/pipx/venvs/ptpython/lib/python3.10/site-packages/pygments/plugin.py in find_plugin_styles()
     61
     62 def find_plugin_styles():
---> 63     for entrypoint in iter_entry_points(STYLE_ENTRY_POINT):
     64         yield entrypoint.name, entrypoint.load()
     65

~/.local/pipx/venvs/ptpython/lib/python3.10/site-packages/pygments/plugin.py in iter_entry_points(group_name)
     43 def iter_entry_points(group_name):
     44     try:
---> 45         import pkg_resources
     46     except (ImportError, OSError):
     47         return []

~/.local/pipx/shared/lib/python3.10/site-packages/pkg_resources/__init__.py in <module>
   3264
   3265 @_call_aside
-> 3266 def _initialize_master_working_set():
   3267     """
   3268     Prepare the master working set and make the ``require()``

~/.local/pipx/shared/lib/python3.10/site-packages/pkg_resources/__init__.py in _call_aside(f, *args, **kwargs)
   3238 # from jaraco.functools 1.3
   3239 def _call_aside(f, *args, **kwargs):
-> 3240     f(*args, **kwargs)
   3241     return f
   3242

~/.local/pipx/shared/lib/python3.10/site-packages/pkg_resources/__init__.py in _initialize_master_working_set()
   3276     at their own risk.
   3277     """
-> 3278     working_set = WorkingSet._build_master()
   3279     _declare_state('object', working_set=working_set)
   3280

~/.local/pipx/shared/lib/python3.10/site-packages/pkg_resources/__init__.py in _build_master(cls)
    562         Prepare the master working set.
    563         """
--> 564         ws = cls()
    565         try:
    566             from __main__ import __requires__

~/.local/pipx/shared/lib/python3.10/site-packages/pkg_resources/__init__.py in __init__(self, entries)
    555
    556         for entry in entries:
--> 557             self.add_entry(entry)
    558
    559     @classmethod

~/.local/pipx/shared/lib/python3.10/site-packages/pkg_resources/__init__.py in add_entry(self, entry)
    611         self.entry_keys.setdefault(entry, [])
    612         self.entries.append(entry)
--> 613         for dist in find_distributions(entry, True):
    614             self.add(dist, entry, False)
    615

~/.local/pipx/shared/lib/python3.10/site-packages/pkg_resources/__init__.py in find_distributions(path_item, only)
   1967 def find_distributions(path_item, only=False):
   1968     """Yield distributions accessible via `path_item`"""
-> 1969     importer = get_importer(path_item)
   1970     finder = _find_adapter(_distribution_finders, importer)
   1971     return finder(importer, path_item, only)

~/.pyenv/versions/3.10.0/lib/python3.10/pkgutil.py in get_importer(path_item)
    419         for path_hook in sys.path_hooks:
    420             try:
--> 421                 importer = path_hook(path_item)
    422                 sys.path_importer_cache.setdefault(path_item, importer)
    423                 break

~/.pyenv/versions/3.10.0/lib/python3.10/importlib/_bootstrap_external.py in path_hook_for_FileFinder(path)

~/.pyenv/versions/3.10.0/lib/python3.10/importlib/_bootstrap_external.py in __init__(self, path, *loader_details)

~/.pyenv/versions/3.10.0/lib/python3.10/importlib/_bootstrap_external.py in _path_isabs(path)

AttributeError: 'PosixPath' object has no attribute 'startswith'

```
</p>
</details>

### Comment

i post this to pygments due to error at the end, which point to this package

if this is not pygments error, please let me know

i will try to catch AttributeError on fork and report the result later

e: 

adding Attribute error and logging to iter_entry_points

```diff
diff --git a/pygments/plugin.py b/pygments/plugin.py
index b1085b7a..6bce778b 100644
--- a/pygments/plugin.py
+++ b/pygments/plugin.py
@@ -34,6 +34,7 @@
     :copyright: Copyright 2006-2021 by the Pygments team, see AUTHORS.
     :license: BSD, see LICENSE for details.
 """
+import logging
 LEXER_ENTRY_POINT = 'pygments.lexers'
 FORMATTER_ENTRY_POINT = 'pygments.formatters'
 STYLE_ENTRY_POINT = 'pygments.styles'
@@ -43,7 +44,8 @@ FILTER_ENTRY_POINT = 'pygments.filters'
 def iter_entry_points(group_name):
     try:
         import pkg_resources
-    except (ImportError, OSError):
+    except (ImportError, OSError, AttributeError) as err:
+        logging.error(err, exc_info=True)
         return []

     return pkg_resources.iter_entry_points(group_name)
```
running ptipython

```python
> poetry run ptipython
/home/r3r/.local/pipx/venvs/ptpython/lib/python3.10/site-packages/IPython/core/interactiveshell.py:934: UserWarning: Attempting to work in a virtualenv. If you encounter problems, please install IPython inside the virtualenv.
  warn("Attempting to work in a virtualenv. If you encounter problems, please "
Error processing line 1 of /home/r3r/.cache/pypoetry/virtualenvs/temp2-Yh2U4OzJ-py3.10/lib/python3.10/site-packages/_virtualenv.pth:

  Traceback (most recent call last):
    File "/home/r3r/.pyenv/versions/3.10.0/lib/python3.10/site.py", line 186, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_virtualenv'

Remainder of file ignored
ERROR:root:'PosixPath' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/home/r3r/.pyenv/versions/3.10.0/lib/python3.10/pkgutil.py", line 417, in get_importer
    importer = sys.path_importer_cache[path_item]
KeyError: PosixPath('/home/r3r/.cache/pypoetry/virtualenvs/temp2-Yh2U4OzJ-py3.10/lib/python3.10/site-packages')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/ac54dceb-73a5-4f94-b52c-cb7a426c0f29/Documents/pygments/pygments/plugin.py", line 46, in iter_entry_points
    import pkg_resources
  File "/home/r3r/.local/pipx/shared/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3266, in <module>
    def _initialize_master_working_set():
  File "/home/r3r/.local/pipx/shared/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3240, in _call_aside
    f(*args, **kwargs)
  File "/home/r3r/.local/pipx/shared/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3278, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/r3r/.local/pipx/shared/lib/python3.10/site-packages/pkg_resources/__init__.py", line 564, in _build_master
    ws = cls()
  File "/home/r3r/.local/pipx/shared/lib/python3.10/site-packages/pkg_resources/__init__.py", line 557, in __init__
    self.add_entry(entry)
  File "/home/r3r/.local/pipx/shared/lib/python3.10/site-packages/pkg_resources/__init__.py", line 613, in add_entry
    for dist in find_distributions(entry, True):
  File "/home/r3r/.local/pipx/shared/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1969, in find_distributions
    importer = get_importer(path_item)
  File "/home/r3r/.pyenv/versions/3.10.0/lib/python3.10/pkgutil.py", line 421, in get_importer
    importer = path_hook(path_item)
  File "<frozen importlib._bootstrap_external>", line 1623, in path_hook_for_FileFinder
  File "<frozen importlib._bootstrap_external>", line 1495, in __init__
  File "<frozen importlib._bootstrap_external>", line 182, in _path_isabs
AttributeError: 'PosixPath' object has no attribute 'startswith'
Python 3.10.0 (default, Nov  7 2021, 13:42:59) [GCC 11.2.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.29.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]:
```

**Comment by rachmadaniHaryono** [comment]
it is quite strange that  ptpython3.9 install with python3.10 on pipx so i just reinstall ptpython with `pipx install --python python3.9 ptpython`
```
   package ptpython 3.0.20, Python 3.10.0
    - ptipython
    - ptipython3
    - ptipython3.9
    - ptpython
    - ptpython3
    - ptpython3.9
    Injected Packages:
      - ipython 7.29.0
```
that fix the error for now

**Comment by Anteru** [comment]
From the call stack it looks like a `PosixPath` is passed in somewhere where a `str` is expected, but the error happens in your installation, not in Pygments (the call stack starts with an `import`.) I suspect it's something in your environment causing this but not Pygments. I don't see how Pygments can cause this so closing for now. I certainly don't think that `import pkg_resources` should fail with an `AttributeError`.
