### ISSUE TITLE
Uncaught exception in get_tokens_unprocessed

### ISSUE THREAD

**Issue by weiweitiantian** [pygments/pygments#1990]
Hello, when I run this testsuite，Uncaught Python exception in get_tokens_unprocessed.
#!/usr/bin/python3

import sys
import atheris
import pygments
import pygments.formatters
import pygments.lexers

def TestOneInput(input_bytes):
  fdp = atheris.FuzzedDataProvider(input_bytes)
  data = fdp.ConsumeUnicode(atheris.ALL_REMAINING)

  try:
    lexer = pygments.lexers.guess_lexer(data)
  except ValueError:
    return
  pygments.highlight(data, lexer, pygments.formatters.HtmlFormatter())

def main():
  atheris.Setup(sys.argv, TestOneInput, enable_python_coverage=True)
  atheris.Fuzz()

if __name__ == "__main__":
  main()

Running: fusiontest-testcase-pygments_fuzzer-202109060001

 === Uncaught Python exception: ===
RecursionError: maximum recursion depth exceeded
Traceback (most recent call last):
  File "pygments_fuzzer.py", line 34, in TestOneInput
    pygments.highlight(data, lexer, pygments.formatters.HtmlFormatter())
  File "/usr/lib/python3.7/site-packages/pygments/__init__.py", line 85, in highlight
    return format(lex(code, lexer), formatter, outfile)
  File "/usr/lib/python3.7/site-packages/pygments/__init__.py", line 64, in format
    formatter.format(tokens, realoutfile)
  File "/usr/lib/python3.7/site-packages/pygments/formatter.py", line 95, in format
    return self.format_unencoded(tokensource, outfile)
  File "/usr/lib/python3.7/site-packages/pygments/formatters/html.py", line 879, in format_unencoded
    for t, piece in source:
  File "/usr/lib/python3.7/site-packages/pygments/formatters/html.py", line 710, in _wrap_div
    for tup in inner:
  File "/usr/lib/python3.7/site-packages/pygments/formatters/html.py", line 728, in _wrap_pre
    for tup in inner:
  File "/usr/lib/python3.7/site-packages/pygments/formatters/html.py", line 753, in _format_lines
    for ttype, value in tokensource:
  File "/usr/lib/python3.7/site-packages/pygments/lexer.py", line 191, in streamer
    for _, t, v in self.get_tokens_unprocessed(text):
  File "/usr/lib/python3.7/site-packages/pygments/lexer.py", line 722, in get_tokens_unprocessed
    for item in action(self, m, ctx):
  File "/usr/lib/python3.7/site-packages/pygments/lexer.py", line 371, in callback
    for i, t, v in lx.get_tokens_unprocessed(match.group(), **gt_kwargs):
  File "/usr/lib/python3.7/site-packages/pygments/lexer.py", line 722, in get_tokens_unprocessed
    for item in action(self, m, ctx):
  File "/usr/lib/python3.7/site-packages/pygments/lexer.py", line 371, in callback
    for i, t, v in lx.get_tokens_unprocessed(match.group(), **gt_kwargs):
  File "/usr/lib/python3.7/site-packages/pygments/lexer.py", line 722, in get_tokens_unprocessed
    for item in action(self, m, ctx):
  File "/usr/lib/python3.7/site-packages/pygments/lexer.py", line 371, in callback
    for i, t, v in lx.get_tokens_unprocessed(match.group(), **gt_kwargs):
  File "/usr/lib/python3.7/site-packages/pygments/lexer.py", line 722, in get_tokens_unprocessed
    for item in action(self, m, ctx):
  File "/usr/lib/python3.7/site-packages/pygments/lexer.py", line 371, in callback
    for i, t, v in lx.get_tokens_unprocessed(match.group(), **gt_kwargs):
  File "/usr/lib/python3.7/site-packages/pygments/lexer.py", line 722, in get_tokens_unprocessed
    for item in action(self, m, ctx):
  File "/usr/lib/python3.7/site-packages/pygments/lexer.py", line 371, in callback
    for i, t, v in lx.get_tokens_unprocessed(match.group(), **gt_kwargs):
  File "/usr/lib/python3.7/site-packages/pygments/lexer.py", line 722, in get_tokens_unprocessed
    for item in action(self, m, ctx):
  File "/usr/lib/python3.7/site-packages/pygments/lexer.py", line 371, in callback
    for i, t, v in lx.get_tokens_unprocessed(match.group(), **gt_kwargs):
  File "/usr/lib/python3.7/site-packages/pygments/lexer.py", line 722, in get_tokens_unprocessed
...
  File "/usr/lib/python3.7/site-packages/pygments/lexer.py", line 371, in callback
    for i, t, v in lx.get_tokens_unprocessed(match.group(), **gt_kwargs):
  File "/usr/lib/python3.7/site-packages/pygments/lexer.py", line 722, in get_tokens_unprocessed
    for item in action(self, m, ctx):
  File "/usr/lib/python3.7/site-packages/pygments/lexer.py", line 371, in callback
    for i, t, v in lx.get_tokens_unprocessed(match.group(), **gt_kwargs):
  File "/usr/lib/python3.7/site-packages/pygments/lexer.py", line 722, in get_tokens_unprocessed
    for item in action(self, m, ctx):
  File "/usr/lib/python3.7/site-packages/pygments/lexer.py", line 371, in callback
    for i, t, v in lx.get_tokens_unprocessed(match.group(), **gt_kwargs):
  File "/usr/lib/python3.7/site-packages/pygments/lexer.py", line 722, in get_tokens_unprocessed
    for item in action(self, m, ctx):
  File "/usr/lib/python3.7/site-packages/pygments/lexer.py", line 371, in callback
    for i, t, v in lx.get_tokens_unprocessed(match.group(), **gt_kwargs):
  File "/usr/lib/python3.7/site-packages/pygments/lexer.py", line 722, in get_tokens_unprocessed
    for item in action(self, m, ctx):
  File "/usr/lib/python3.7/site-packages/pygments/lexer.py", line 371, in callback
    for i, t, v in lx.get_tokens_unprocessed(match.group(), **gt_kwargs):
  File "/usr/lib/python3.7/site-packages/pygments/lexer.py", line 722, in get_tokens_unprocessed
    for item in action(self, m, ctx):
  File "/usr/lib/python3.7/site-packages/pygments/lexer.py", line 371, in callback
    for i, t, v in lx.get_tokens_unprocessed(match.group(), **gt_kwargs):
  File "/usr/lib/python3.7/site-packages/pygments/lexer.py", line 707, in get_tokens_unprocessed
    ctx = LexerContext(text, 0)

==13230== ERROR: libFuzzer: fuzz target exited
SUMMARY: libFuzzer: fuzz target exited

**Comment by birkenfeld** [comment]
Thanks for the report, it is however impossible to fix without the fuzzer input.

**Comment by Jean-Abou-Samra** [comment]
Closing as there wasn't information on how to reproduce.
