### ISSUE TITLE
Support new versions of Python

### ISSUE THREAD

**Issue by Sid110307** [pygments/pygments#2007]
When I use `pygmentize -g` with a file, I get this error:

```
pkg_resources.DistributionNotFound: The 'backports.functools-lru-cache>=1.2.1; python_version < "3.2"' distribution was not found and is required by wcwidth
```

I have Python 3.10 installed.
This is the whole traceback:

```
pc@mypc:~$ pygmentize -g test.html -v

*****************************************************************
An unhandled exception occurred while highlighting.
Please report the whole traceback to the issue tracker at
<https://github.com/pygments/pygments/issues>.
*****************************************************************

Traceback (most recent call last):
  File "/home/pc/.local/bin/pygmentize", line 8, in <module>
    sys.exit(main())
  File "/home/pc/.local/lib/python3.10/site-packages/pygments/cmdline.py", line 577, in main
    return main_inner(parser, argns)
  File "/home/pc/.local/lib/python3.10/site-packages/pygments/cmdline.py", line 305, in main_inner
    lexer = get_lexer_for_filename(infn, code, **parsed_opts)
  File "/home/pc/.local/lib/python3.10/site-packages/pygments/lexers/__init__.py", line 207, in get_lexer_for_filename
    res = find_lexer_class_for_filename(_fn, code)
  File "/home/pc/.local/lib/python3.10/site-packages/pygments/lexers/__init__.py", line 172, in find_lexer_class_for_filename
    for cls in find_plugin_lexers():
  File "/home/pc/.local/lib/python3.10/site-packages/pygments/plugin.py", line 54, in find_plugin_lexers
    yield entrypoint.load()
  File "/home/pc/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2442, in load
    self.require(*args, **kwargs)
  File "/home/pc/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2465, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/pc/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'backports.functools-lru-cache>=1.2.1; python_version < "3.2"' distribution was not found and is required by wcwidth
```

I think this has got to do with a new version of Python.

**Comment by Chzjc** [comment]
hi sid，excuse me，How to solve this problem？update or downgrade version of Python？

**Comment by Sid110307** [comment]
Update your python version to a stable one. I think it was because I had installed a development version of python.
