### ISSUE TITLE
Error when running any `pygmentize` command | MacOS

### ISSUE THREAD

**Issue by bennodev19** [pygments/pygments#2093]
Hello there,
I'm facing an issue (See `Error message`) when I run any `pygmentize` command on MacOS.
I've installed `pygments` earlier this day via:
```
sudo easy_install Pygments
```

###  🔴 Error message:
```
➜  src git:(master) ✗ pygmentize -V
Traceback (most recent call last):
  File "/usr/local/bin/pygmentize", line 11, in <module>
    load_entry_point('Pygments==2.11.2', 'console_scripts', 'pygmentize')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Python/2.7/site-packages/Pygments-2.11.2-py2.7.egg/pygments/cmdline.py", line 83
    print("%s not found!" % what, file=sys.stderr)
```

### 💻 Environment
MacOS: 11.6.1 (20G224)
Python: 2.7.16

**Comment by Jean-Abou-Samra** [comment]
We no longer support Python 2. Please use Python 3. Thanks.

**Comment by bennodev19** [comment]
looks like I'm getting the same error, after updating to the latest version (`3.10`) :/

<img width="1152" alt="Bildschirmfoto 2022-03-21 um 19 56 42" src="https://user-images.githubusercontent.com/57860196/159344619-318753ce-2503-4a34-82cd-8d60b8cace36.png">

**Comment by bennodev19** [comment]
Alright, with the correct python version it works as expected.. Thanks ;D

In case sb is facing the same issue and needs to update python on their macOS (Big Sur) too,
this tutorial worked for me: https://www.youtube.com/watch?v=0rg6nyanX5Y
