### ISSUE TITLE
Error reading page: format() argument must be a formatter instance, not a class

### ISSUE THREAD

**Issue by Lucas-C** [pygments/pygments#2119]
Hi

Since the release of pygments 2.12.0, my `mkdocs`-based documentation build is failing:
https://github.com/PyFPDF/fpdf2/runs/6149548887

Detailed stacktrace:
```
ERROR    -  Error reading page 'Development.md': format() argument must be a formatter instance, not a class
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/pygments/__init__.py", line 61, in format
    formatter.format(tokens, realoutfile)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/pygments/formatter.py", line 94, in format
    return self.format_unencoded(tokensource, outfile)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/pygments/formatters/html.py", line 981, in format_unencoded
    source = self.wrap(source)
TypeError: BlockHtmlFormatter.wrap() missing 1 required positional argument: 'outfile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/mkdocs/__main__.py", line 192, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/mkdocs/commands/build.py", line 292, in build
    _populate_page(file.page, config, files, dirty)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/mkdocs/commands/build.py", line 174, in _populate_page
    page.render(config, files)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/mkdocs/structure/pages.py", line 175, in render
    self.content = md.convert(self.markdown)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/markdown/core.py", line 268, in convert
    newRoot = treeprocessor.run(root)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/pymdownx/highlight.py", line 491, in run
    code.highlight(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/pymdownx/highlight.py", line 392, in highlight
    code = highlight(src, lexer, formatter)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/pygments/__init__.py", line 82, in highlight
    return format(lex(code, lexer), formatter, outfile)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/pygments/__init__.py", line 69, in format
    raise TypeError('format() argument must be a formatter instance, '
TypeError: format() argument must be a formatter instance, not a class
```

The Markdown document triggering this error is there: https://github.com/PyFPDF/fpdf2/blob/master/docs/Development.md

I'm going to try to reproduce this locally, and to narrow the problem to a minimal source file...

**Comment by Jean-Abou-Samra** [comment]
This is expected. Please see the Changelog:

https://github.com/pygments/pygments/blob/master/CHANGES#L66

#2101 has the context on this change.

**Comment by Lucas-C** [comment]
There is a minimal `mkdocs.yml`:
```yaml
site_name: fpdf2
docs_dir: docs/
markdown_extensions: [pymdownx.highlight]
nav:
- 'Development': 'Development.md'
```

And minimal `Development.md`:
```markdown

    mkdocs serve

```

**Comment by Jean-Abou-Samra** [comment]
To expand a little more:

The signature of `Formatter.wrap()` changed, it needs to be adapted in subclasses.

It appears that mkdocs-material has already updated its requirements as a temporary measure:

https://github.com/squidfunk/mkdocs-material/commit/85b087ac942999bfc16224e637596f67d87094bb

So I suppose you need to update mkdocs-material.

**Comment by Lucas-C** [comment]
Seems like this PR solves my issue: https://github.com/facelessuser/pymdown-extensions/pull/1666

I tested it this way:

	pip install -U https://github.com/facelessuser/pymdown-extensions/archive/main.tar.gz

So I guess now we need to wait for a new release of `pymdown-extensions`...

**Comment by Jean-Abou-Samra** [comment]
Not necessarily: you could pin your own requirements in the meantime.

```
pip install --user --upgrade pygments==2.11 pymdown-extensions==9.3
```

That way, it will use an older Pygments. Once there is a release of `pydown-extensions` with the fix you mention, you can change this to

```
pip install --user --upgrade pygments==2.12 pymdown-extensions==the-new-version
```

The part after `pip install --user --upgrade` can go in your `requirements.txt` file (or whatever method you're using to specify doc build requirements).

**Comment by fluffy-critter** [comment]
Would it have been possible for the exception message and/or changelog entry to include a link to something indicating the actual API change? The fix was pretty easy once I knew what to do, but tracking down what actually changed took a decent amount of time.

Also, under https://pygments.org/docs/formatters/#HtmlFormatter it might be helpful to add an `id="HtmlFormatter_subclassing"` to the subheading for "Subclassing the HTML formatter" so that the link can go more directly there.

Thanks!

**Comment by Jean-Abou-Samra** [comment]
#2123 should start improving the error message by not confusing you with 'should be a formatter instance, not a class'.

@Anteru It looks like the doc example ran out of sync with the code, it has an `include_div` kwarg which has been removed from the iteration of #2101. Could you take a look?
