### ISSUE TITLE
make mapfiles error

### ISSUE THREAD

**Issue by petelomax** [pygments/pygments#2221]
Seems to me like it's saying that it can't find the thing that it just found:
>make mapfiles
python3 scripts/gen_mapfiles.py
The system cannot find the path specified.
pygments.lexers.actionscript
pygments.lexers.ada
...
pygments.lexers.perl
pygments.lexers.phix
Traceback (most recent call last):
  File "E:\downloads\misc\pygments\scripts\gen_mapfiles.py", line 53, in <module>
    main()
  File "E:\downloads\misc\pygments\scripts\gen_mapfiles.py", line 28, in main
    module = import_module(module_name)
  File "C:\Program Files\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'pygments.lexers.phix'
make: *** [mapfiles] Error 1

ProcMon says it's looking for E:\downloads\misc\pygments\\\<frozen importlib._bootstrap\> and getting NAME_INVALID.

**Comment by petelomax** [comment]
Same result at the end (obvs), but it now starts with:
The system cannot find the path specified.
E:\downloads\misc\pygments\scripts\gen_mapfiles.py E:\downloads\misc\pygments E:\downloads\misc\pygments\pygments E:\downloads\misc\pygments\pygments True True
pygments.lexers.actionscript
pygments.lexers.ada
...

HTH

**Comment by petelomax** [comment]
OK, let's step back a minute. The opening error is a potential clue, but not a blocking problem, whereas the final one is.

I now believe the opening error occurs somewhere within make itself:
E:\downloads\misc\pygments>make
find . -name '__pycache__' -exec rm -rf {} +
The system cannot find the path specified.
FIND: Parameter format not correct
make: *** [clean-pyc] Error 2

However, it looks like make is coping/ignoring it and carrying on.

Re-running "choco install make" has no effect whatsoever.
I also tried opening a WSL terminal and running it from there, only to get:
  File "scripts/gen_mapfiles.py", line 38
    lines.append(f'    {obj_name!r}: {desc!r},')
                                              ^
SyntaxError: invalid syntax (pointing at the closing quote)

So (with all WSL attempts abandoned) my question now is: should running python3 scripts/gen_mapfiles.py directly work?
If I try that, I get no opening error/clue, but the same final blocking problem, ie ModuleNotFoundError: No module named 'pygments.lexers.phix'

E:\downloads\misc\pygments>py
Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)] on win32
E:\downloads\misc\pygments>python
Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)] on win32
E:\downloads\misc\pygments>python3
Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)] on win32

There are other versions of python on this box too, but since my path **starts** as follows:
E:\downloads\misc\pygments>set
Path=C:\Program Files\Python310\Scripts\;C:\Program Files\Python310\;C:\Program Files (x86)\Python37-32\Scripts\;C:\Program Files (x86)\Python37-32\;C:\Python27\;C:\Python27\Scripts;C:\WINDOWS\system32;...

I struggle to imagine why they'd be a problem, plus under WSL I tried both 2.7.6 and 3.4.3, to no avail.

I suspect I'm just simply going to have to submit a pull request but without running any of the tests..

**Comment by petelomax** [comment]
C:\Users\Pete\AppData\Roaming\Python\Python310\site-packages\pygments\__init__.py

I can confirm, despite the path mangling above, that file does exist, and it is version 2.13.0, and in fact identical to the one in
E:\downloads\misc\pygments\pygments\__init__.py - and it would explain things if it's getting a bit lost because Windows has reparsed it there, for reasons I can't fathom (access permissions seem fine, full read/write for everyone) - hang on, surely it should be trying to load that from E:\downloads, not C:\Program Files?

Also, I've run "make -d" which seems to confirm your suspicion regarding the makefile being Windows-unfriendly:
... (as per above)
find . -name '__pycache__' -exec rm -rf {} +
...
Creating temporary batch file C:\Users\Pete\AppData\Local\Temp\make9624-1.bat
Batch file contents:
        @echo off
        python -c 'import os; print ":".join(os.path.abspath(line.strip()) for line in file("PYTHONPATH"))' 2>/dev/null
CreateProcess(C:\Users\Pete\AppData\Local\Temp\make9624-1.bat,C:\Users\Pete\AppData\Local\Temp\make9624-1.bat,...)
The system cannot find the path specified.
Cleaning up temporary batch file C:\Users\Pete\AppData\Local\Temp\make9624-1.bat

So, yeah, I'd guess that initial message just means that /dev/null does not exist on Windows, and cmd.exe cops out when it can't redirect the error output without even running that line. The offending line is export PYTHONPATH in the makefile, I tried removing just the 2> part but got slapped with "SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?", so instead removed the whole line (and set PYTHONPATH manually) and, lo, the initial error has gone.

**Comment by petelomax** [comment]
Thanks, that works. Of course I've just run headlong into make tests.
There is no which command in windows, so I just ran 'pytest tests' instead:

>E:\downloads\misc\pygments>pytest tests
================================================ test session starts ================================================
platform win32 -- Python 3.10.4, pytest-7.1.2, pluggy-1.0.0
rootdir: E:\downloads\misc\pygments
collected 3924 items / 2 errors

>`===================================================== ERRORS =======================================================
__________________________ ERROR collecting tests/test_html_formatter_linenos_elements.py ___________________________
ImportError while importing test module 'E:\downloads\misc\pygments\tests\test_html_formatter_linenos_elements.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
C:\Program Files\Python310\lib\importlib\__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests\test_html_formatter_linenos_elements.py:9: in <module>
    from .support import structural_diff
tests\support\structural_diff.py:1: in <module>
    import lxml.html
E   ModuleNotFoundError: No module named 'lxml'
_________________________________ ERROR collecting tests/contrast/test_contrasts.py _________________________________
ImportError while importing test module 'E:\downloads\misc\pygments\tests\contrast\test_contrasts.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
C:\Program Files\Python310\lib\importlib\__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests\contrast\test_contrasts.py:18: in <module>
    import wcag_contrast_ratio
E   ModuleNotFoundError: No module named 'wcag_contrast_ratio'
============================================== short test summary info ==============================================
ERROR tests/test_html_formatter_linenos_elements.py
ERROR tests/contrast/test_contrasts.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================================= 2 errors in 6.94s =================================================`

Hopefully that's something rather similar

**Comment by petelomax** [comment]
Thanks, that helped. I left pytest running for about five hours before investigating further, and it was stuck in an infinite loop trying to create some temp files in Program Files\Python310, so I granted it access permissions and it then finished ok.
