### ISSUE TITLE
HtmlFormatter.wrap pyi stub file signature not matching method

### ISSUE THREAD

**Issue by fraser-langton** [pygments/pygments#2264]
```
Traceback (most recent call last):
  ...
  File "/home/ec2-user/.local/share/virtualenvs/orm_btp_AEBP-24_new_form_updater-8A8U1H_m/lib/python3.8/site-packages/pygments/__init__.py", line 82, in highlight
    return format(lex(code, lexer), formatter, outfile)
  File "/home/ec2-user/.local/share/virtualenvs/orm_btp_AEBP-24_new_form_updater-8A8U1H_m/lib/python3.8/site-packages/pygments/__init__.py", line 61, in format
    formatter.format(tokens, realoutfile)
  File "/home/ec2-user/.local/share/virtualenvs/orm_btp_AEBP-24_new_form_updater-8A8U1H_m/lib/python3.8/site-packages/pygments/formatter.py", line 94, in format
    return self.format_unencoded(tokensource, outfile)
  File "/home/ec2-user/.local/share/virtualenvs/orm_btp_AEBP-24_new_form_updater-8A8U1H_m/lib/python3.8/site-packages/pygments/formatters/html.py", line 981, in format_unencoded
    source = self.wrap(source)
TypeError: wrap() missing 1 required positional argument: 'outfile'
```

In stubs/Pygments/pygments/formatters/html.pyi file I see
`    def wrap(self, source, outfile): ...`
In pygments/formatters/html.py I see
`    def wrap(self, source):`

Example file that raises the error
```
from pygments.formatters.html import HtmlFormatter

class MyFormatter(HtmlFormatter):

    def wrap(self, source):
        super().wrap(source)
```

![image](https://user-images.githubusercontent.com/39111573/198167051-0de69216-6feb-4032-8586-58af86b90672.png)

**Comment by birkenfeld** [comment]
This API has changed in version 2.12, PR#2101. We don't maintain the stubs, so please report to their provider.
