### ISSUE TITLE
2.14.0: documentation build fails

### ISSUE THREAD

**Issue by kloczek** [pygments/pygments#2312]
Looks like something recently has changed because now documetation build fails with
```console
+ /usr/bin/sphinx-build -n -T -b man doc build/sphinx/man
Running Sphinx v5.3.0
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 28 added, 0 changed, 0 removed
reading sources... [ 96%] languages
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 281, in build_main
    app.build(args.force_all, args.filenames)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 347, in build
    self.builder.build_update()
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 307, in build_update
    self.build(['__all__'], to_build)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 326, in build
    updated_docnames = set(self.read())
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 433, in read
    self._read_serial(docnames)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 454, in _read_serial
    self.read_doc(docname)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 510, in read_doc
    publisher.publish()
  File "/usr/lib/python3.8/site-packages/docutils/core.py", line 224, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "/usr/lib/python3.8/site-packages/sphinx/io.py", line 104, in read
    self.parse()
  File "/usr/lib/python3.8/site-packages/docutils/readers/__init__.py", line 76, in parse
    self.parser.parse(self.input, document)
  File "/usr/lib/python3.8/site-packages/sphinx/parsers.py", line 78, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 169, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2785, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 325, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 391, in new_subsection
    newabsoffset = self.nested_parse(
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 279, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2355, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2367, in explicit_construct
    return method(self, expmatch)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2104, in directive
    return self.run_directive(
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2154, in run_directive
    result = directive_instance.run()
  File "/usr/lib/python3.8/site-packages/pygments/sphinxext.py", line 78, in run
    raise Exception('invalid argument for "pygmentsdoc" directive')
Exception: invalid argument for "pygmentsdoc" directive

Exception occurred:
  File "/usr/lib/python3.8/site-packages/pygments/sphinxext.py", line 78, in run
    raise Exception('invalid argument for "pygmentsdoc" directive')
Exception: invalid argument for "pygmentsdoc" directive
The full traceback has been saved in /tmp/sphinx-err-c8js501f.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**Comment by Anteru** [comment]
Cannot reproduce:

```
$ sphinx-build -b man . build/man
Running Sphinx v6.0.0
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 28 added, 0 changed, 0 removed
reading sources... [100%] styles
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... pygments.1 { download docs/quickstart docs/cmdline docs/lexers docs/filters docs/formatters docs/styles docs/unicode docs/tokens docs/api docs/terminal-sessions docs/lexerdevelopment docs/formatterdevelopment docs/filterdevelopment docs/styledevelopment docs/plugins docs/rstdirective docs/moinmoin docs/java docs/integrate docs/changelog docs/authors docs/security } done
build succeeded.

The manual pages are in build/man.
```

(This is running from the `./doc` folder) Can you please try if that works for you? It looks like you're using some outdated code because line 78 doesn't raise the exception, the exception is in line 80.

**Comment by kloczek** [comment]
Just tested with latest sphinx and looks lie it works however I see some nitpick warnings (result of using `-n` option)
```console
+ /usr/bin/sphinx-build -n -T -b man doc build/sphinx/man
Running Sphinx v5.3.0
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 28 added, 0 changed, 0 removed
reading sources... [100%] styles
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... python-pygments.3 { download docs/quickstart docs/cmdline docs/lexers docs/filters docs/formatters docs/styles docs/unicode docs/tokens docs/api docs/terminal-sessions docs/lexerdevelopment docs/formatterdevelopment docs/filterdevelopment docs/styledevelopment docs/plugins docs/rstdirective docs/moinmoin docs/java docs/integrate docs/changelog docs/authors docs/security } /home/tkloczko/rpmbuild/BUILD/pygments-2.14.0/doc/docs/quickstart.rst:61: WARNING: py:func reference target not found: get_style_defs
/home/tkloczko/rpmbuild/BUILD/pygments-2.14.0/doc/docs/quickstart.rst:74: WARNING: py:func reference target not found: highlight
/home/tkloczko/rpmbuild/BUILD/pygments-2.14.0/doc/docs/quickstart.rst:156: WARNING: py:meth reference target not found: analyse_text
/home/tkloczko/rpmbuild/BUILD/pygments-2.14.0/doc/docs/styles.rst:80: WARNING: py:attr reference target not found: pygments.style.ansicolors
/home/tkloczko/rpmbuild/BUILD/pygments-2.14.0/doc/docs/api.rst:3: WARNING: py:exc reference target not found: pygments.util.ClassNotFound
/home/tkloczko/rpmbuild/BUILD/pygments-2.14.0/doc/docs/api.rst:3: WARNING: py:exc reference target not found: pygments.util.ClassNotFound
/home/tkloczko/rpmbuild/BUILD/pygments-2.14.0/doc/docs/api.rst:2: WARNING: py:exc reference target not found: pygments.util.ClassNotFound
/home/tkloczko/rpmbuild/BUILD/pygments-2.14.0/doc/docs/api.rst:5: WARNING: py:exc reference target not found: ClassNotFound
/home/tkloczko/rpmbuild/BUILD/pygments-2.14.0/doc/docs/api.rst:4: WARNING: py:exc reference target not found: pygments.util.ClassNotFound
/home/tkloczko/rpmbuild/BUILD/pygments-2.14.0/doc/docs/api.rst:2: WARNING: py:exc reference target not found: pygments.util.ClassNotFound
/home/tkloczko/rpmbuild/BUILD/pygments-2.14.0/doc/docs/api.rst:2: WARNING: py:exc reference target not found: pygments.util.ClassNotFound
/home/tkloczko/rpmbuild/BUILD/pygments-2.14.0/doc/docs/api.rst:2: WARNING: py:exc reference target not found: pygments.util.ClassNotFound
/home/tkloczko/rpmbuild/BUILD/pygments-2.14.0/doc/docs/api.rst:2: WARNING: py:exc reference target not found: pygments.util.ClassNotFound
/home/tkloczko/rpmbuild/BUILD/pygments-2.14.0/doc/docs/api.rst:5: WARNING: py:exc reference target not found: ClassNotFound
/home/tkloczko/rpmbuild/BUILD/pygments-2.14.0/<rst_prolog>:1: WARNING: py:data reference target not found: pygments.styles.STYLE_MAP
/home/tkloczko/rpmbuild/BUILD/pygments-2.14.0/doc/docs/api.rst:2: WARNING: py:exc reference target not found: pygments.util.ClassNotFound
/home/tkloczko/rpmbuild/BUILD/pygments-2.14.0/<rst_prolog>:1: WARNING: py:meth reference target not found: __init__
/home/tkloczko/rpmbuild/BUILD/pygments-2.14.0/<rst_prolog>:1: WARNING: py:mod reference target not found: fnmatch
/home/tkloczko/rpmbuild/BUILD/pygments-2.14.0/doc/docs/lexerdevelopment.rst:26: WARNING: py:class reference target not found: RegexLexer
/home/tkloczko/rpmbuild/BUILD/pygments-2.14.0/doc/docs/lexerdevelopment.rst:133: WARNING: py:class reference target not found: pygments.formatters.html.HtmlFormatter
done
build succeeded, 20 warnings.
```
Fixes of simillar issue in other projects
https://github.com/latchset/jwcrypto/pull/289
https://github.com/click-contrib/sphinx-click/commit/abc31069
https://github.com/latchset/jwcrypto/pull/289
https://github.com/RDFLib/rdflib-sqlalchemy/issues/95
https://github.com/sissaschool/elementpath/commit/bf869d9e
https://github.com/jaraco/cssutils/issues/21
https://github.com/pywbem/pywbem/pull/2895
https://github.com/sissaschool/xmlschema/commit/42ea98f2
https://github.com/RDFLib/rdflib/pull/2036
https://github.com/frostming/unearth/issues/14
https://github.com/pypa/distlib/commit/98b9b89f

**Comment by birkenfeld** [comment]
Reopening to track the build warnings.

**Comment by kloczek** [comment]
Just tested master commkts and it looks way better now howeverf there atill some warnings 😋 
```console
Running Sphinx v6.1.3
making output directory... done
building [mo]: targets for 0 po files that are out of date
writing output...
building [man]: all manpages
updating environment: [new config] 29 added, 0 changed, 0 removed
reading sources... [100%] styles
/usr/lib/python3.8/site-packages/pygments/lexer.py:docstring of pygments.lexer.Lexer.__init__:14: ERROR: Unknown target name: "option processing".
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... python-pygments.3 { download docs/quickstart docs/cmdline docs/lexers docs/filters docs/formatters docs/styles docs/unicode docs/tokens docs/api docs/terminal-sessions docs/lexerdevelopment docs/formatterdevelopment docs/filterdevelopment docs/styledevelopment docs/plugins docs/rstdirective docs/moinmoin docs/java docs/integrate docs/contributing docs/changelog docs/authors docs/security } /home/tkloczko/rpmbuild/BUILD/pygments-2.15.0/doc/docs/styles.rst:80: WARNING: py:data reference target not found: pygments.style.ansicolors
/usr/lib/python3.8/site-packages/pygments/formatter.py:docstring of pygments.formatter.Formatter:1: WARNING: py:class reference target not found: lexer.Lexer
/usr/lib/python3.8/site-packages/pygments/formatter.py:docstring of pygments.formatter.Formatter.filenames:1: WARNING: py:mod reference target not found: fnmatch
done
build succeeded, 4 warnings.
```
