### ISSUE TITLE
encoding argument ignored for input on stdin

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#506]
(Original issue 799 created by rrt on 2012-08-19T20:32:18.840276+00:00)

According to the documentation:

 * If you give an encoding option, it will be used as the input and output encoding.
 * If you give an outencoding option, it will override encoding as the output encoding.

So, I run:

  $ pygmentize -O encoding=iso-8859-1,outencoding=UTF-8 -l latex microtype.dtx

and it works fine. (Incidentally, the file I am using for testing is here:

http://anorien.csc.warwick.ac.uk/mirrors/CTAN/macros/latex/contrib/microtype/microtype.dtx

.) But if instead I run:

  $ cat microtype.dtx | pygmentize -O encoding=iso-8859-1,outencoding=UTF-8 -l latex

Then I get the following error:

Traceback (most recent call last):
  File "/home/rrt/.local/bin/pygmentize", line 9, in <module>
    load_entry_point('Pygments==1.5', 'console_scripts', 'pygmentize')()
  File "/home/rrt/.local/lib/python3.2/site-packages/Pygments-1.5-py3.2.egg/pygments/cmdline.py", line 395, in main
    code = sys.stdin.read()
  File "/usr/lib/python3.2/codecs.py", line 300, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 17827: invalid start byte

Apparently when reading from stdin, pygments is ignoring the encoding argument and using the terminal encoding (I'm on a UTF-8 terminal).

**Comment by Anteru** [comment]
(Original comment by birkenfeld on 2013-01-09T15:39:32.322629+00:00)

Can't reproduce here with a latin-1 encoded file and utf-8 terminal.

**Comment by Anteru** [comment]
(Original comment by rrt on 2013-01-10T15:02:29.108821+00:00)

I just tried with 1.6rc1 and indeed the problem is fixed (I confirmed that it was still there in 1.5!).

**Comment by Anteru** [comment]
(Original comment by rrt on 2013-01-10T15:15:45.634581+00:00)

In fact, I just tried again and had the same problem. In fact, the problem is caused by using Python 3.2; if I use Python 2.7 I don't get the problem.

**Comment by Anteru** [comment]
(Original comment by birkenfeld on 2014-10-07T22:30:42.593170+00:00)

Closes #799: read from binary buffer stdin on Python 3 if explicit encoding given

→ <<cset 36a82018ed9f>>
