### ISSUE TITLE
Test errors with Python 2.6

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#748]
(Original issue 1041 created by arfrever on 2014-10-07T15:18:01.694111+00:00)

Pygments trunk has 7 errors in test suite with Python 2.6.

(0 errors and failures with Python 2.7, 3.3, 3.4.)

```
======================================================================
ERROR: test_randomly (test_regexopt.RegexOptTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/pygments-main/tests/test_regexopt.py", line 32, in test_randomly
    kwlist = self.generate_keywordlist(n)
  File "/tmp/pygments-main/tests/test_regexopt.py", line 25, in generate_keywordlist
    itertools.combinations_with_replacement(ALPHABET, length)]
AttributeError: 'module' object has no attribute 'combinations_with_replacement'

======================================================================
ERROR: test_endswith_correct (test_string_asserts.TestStringTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/pygments-main/tests/test_string_asserts.py", line 29, in test_endswith_correct
    self.assertEndsWith("AAA", "A")
  File "/tmp/pygments-main/tests/string_asserts.py", line 20, in assertEndsWith
    msg = "'{}' does not end with '{}'".format(haystack, needle)
ValueError: zero length field name in format

======================================================================
ERROR: test_endswith_incorrect (test_string_asserts.TestStringTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/pygments-main/tests/test_string_asserts.py", line 33, in test_endswith_incorrect
    with self.assertRaises(AssertionError):
TypeError: failUnlessRaises() takes at least 3 arguments (2 given)

======================================================================
ERROR: test_endswith_short (test_string_asserts.TestStringTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/pygments-main/tests/test_string_asserts.py", line 38, in test_endswith_short
    with self.assertRaises(AssertionError):
TypeError: failUnlessRaises() takes at least 3 arguments (2 given)

======================================================================
ERROR: test_startswith_correct (test_string_asserts.TestStringTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/pygments-main/tests/test_string_asserts.py", line 16, in test_startswith_correct
    self.assertStartsWith("AAA", "A")
  File "/tmp/pygments-main/tests/string_asserts.py", line 14, in assertStartsWith
    msg = "'{}' does not start with '{}'".format(haystack, needle)
ValueError: zero length field name in format

======================================================================
ERROR: test_startswith_incorrect (test_string_asserts.TestStringTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/pygments-main/tests/test_string_asserts.py", line 20, in test_startswith_incorrect
    with self.assertRaises(AssertionError):
TypeError: failUnlessRaises() takes at least 3 arguments (2 given)

======================================================================
ERROR: test_startswith_short (test_string_asserts.TestStringTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/pygments-main/tests/test_string_asserts.py", line 25, in test_startswith_short
    with self.assertRaises(AssertionError):
TypeError: failUnlessRaises() takes at least 3 arguments (2 given)

----------------------------------------------------------------------
Ran 1493 tests in 37.448s

FAILED (errors=7)
```

**Comment by Anteru** [comment]
(Original comment by birkenfeld on 2014-10-07T15:42:53.742803+00:00)

Closes #1041: Fix test suite to pass under Python 2.6.

→ <<cset efa0b234a9e0>>

**Comment by Anteru** [comment]
(Original comment by birkenfeld on 2014-10-07T15:43:10.241506+00:00)

Thanks. I hope this fixes it.

**Comment by Anteru** [comment]
(Original comment by arfrever on 2014-10-07T15:57:55.079228+00:00)

I confirm that all tests now pass.
