### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#941]
(Original issue 1234 created by willx on 2016-04-25T23:38:58.291007+00:00)

Getting the below error (input, attached, is from "port search capn" on OS X 10.11.4, macports 2.3.4), using macports py27-pygments 2.1.3:

```
#!text
capnproto @0.5.2 (devel)

*****************************************************************
An unhandled exception occurred while highlighting.
Please report the whole traceback to the issue tracker at
<https://bitbucket.org/birkenfeld/pygments-main/issues>.
*****************************************************************

CapTraceback (most recent call last):
  File "/opt/local/bin/pygmentize-2.7", line 9, in <module>
    load_entry_point('Pygments==2.1.3', 'console_scripts', 'pygmentize')()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pygments/cmdline.py", line 504, in main
    return main_inner(popts, args, usage)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pygments/cmdline.py", line 468, in main_inner
    highlight(code, lexer, fmter, outfile)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pygments/__init__.py", line 87, in highlight
    return format(lex(code, lexer), formatter, outfile)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pygments/__init__.py", line 69, in format
    formatter.format(tokens, outfile)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pygments/formatters/terminal.py", line 101, in format
    return Formatter.format(self, tokensource, outfile)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pygments/formatter.py", line 95, in format
    return self.format_unencoded(tokensource, outfile)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pygments/formatters/terminal.py", line 126, in format_unencoded
    outfile.write(ansiformat(color, line.rstrip('\n')))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py", line 369, in write
    data, consumed = self.encode(object, self.errors)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 13: ordinal not in range(128)
```

**Comment by Anteru** [comment]
(Original comment by tshatch on 2016-06-01T08:03:44.629350+00:00)

My guess is that it takes input with utf-8 and is piping it without specifying an output encoding.
