### ISSUE TITLE
test_basic_api can fail for Angular2

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments#992]
(Original issue 1288 created by roskakori on 2016-10-01T05:46:44.843032+00:00)

When running the whole test suite during testing one of my changes I noticed that `test_basic_api` failed for Angular2 and Angula2+HTML.

As this seems to be a test with random text, it does not always fail, so here's the specific output of the failed run:

```
FAIL: test_basic_api.test_lexer_classes(<class 'pygments.lexers.templates.Angular2HtmlLexer'>,)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File ".../tests/test_basic_api.py", line 81, in verify
    (cls.name, test_content, txt)
AssertionError: HTML + Angular2 lexer roundtrip failed: 'a.g>j`bdBjF~{/{)]M|\x7fayqpU_\';Ok9_FTRw>5[^k_6-?*ECO$>bUR-Zxe7\\VqL1Z[N4_^\x7fnx%eT*}ANR@4<*KS:XP\\N/?:gBy&45N\'>]W.&W;7:8/zo|;c\'&XFm1}lx9(vnDH_jtc&l!^8Eu)\x7fdDsSW4W@M&wK.iEfMWbMiPU#^%R,t~<5HI{n:}ug3f!;7y<\x7fO0E\\;i^qIlvxekI,7~c2|C|+h/Vv3<C6o+=CvH"m`k0`)Sr8V?syr"QQ8izAGTPph=2QltIKpGMmVsT0hd*0!\\36L>1)k#9]C~scgb%u!@r!Gzm2m#z$Hdlf[2F.j=r(ZK]YeY[iZ\'Y,L,XUffGB)G-j$`{w5}P?S@0=Jgu1q<S~4:qbt9aBwZ-uwA+YP*x.zT?-(h/A%3F\x7fKO"s"#Urc6OHE}VB8RYJD$IX+QDet9n`J|"D\\oLXv\'pon725p@$N%J6]Q({[A3(ad,1Jyo+aL#h=\n' != 'a.g>j`bdBjF~{/{)]M|\x7fayqpU_\';Ok9_FTRw>5[^k_6-?*ECO$>bUR-Zxe7\\VqL1Z[N4_^\x7fnx%eT*}ANR@4<*KS:XP\\N/?:gBy&45N\'>]W.&W;7:8/zo|;c\'&XFm1}lx9(vnDH_jtc&l!^8Eu)\x7fdDsSW4W@M&wK.iEfMWbMiPU#^%R,t~<5HI{n:}ug3f!;7y<\x7fO0E\\;i^qIlvxekI,7~c2|C|+h/Vv3<C6o+=CvH"m`k0`)Sr8V?syr"QQ8izAGTPph=2QltIKpGMmVsT0hd*0!\\36L>1)k#9]C~scgb%u!@r!Gzm2m#z$Hdlf[2F.j=r(ZK]YeY[iZ\'Y,L,XUffGB)G-j$`{w5}P?S@0=Jgu1q<S~4:qbt9aBwZ-uwA+YP*x.zT?-(h/A%3F\x7fKO"s"#Urc6OHE}VB8RYJD$IX+QDet9n`J|"D\\oLXv\'pon725p@$N%J6]Q({[A3(ad,1Jyo+aL#h='
>>  assert 'a.g>j`bdBjF~{/{)]M|\x7fayqpU_\';Ok9_FTRw>5[^k_6-?*ECO$>bUR-Zxe7\\VqL1Z[N4_^\x7fnx%eT*}ANR@4<*KS:XP\\N/?:gBy&45N\'>]W.&W;7:8/zo|;c\'&XFm1}lx9(vnDH_jtc&l!^8Eu)\x7fdDsSW4W@M&wK.iEfMWbMiPU#^%R,t~<5HI{n:}ug3f!;7y<\x7fO0E\\;i^qIlvxekI,7~c2|C|+h/Vv3<C6o+=CvH"m`k0`)Sr8V?syr"QQ8izAGTPph=2QltIKpGMmVsT0hd*0!\\36L>1)k#9]C~scgb%u!@r!Gzm2m#z$Hdlf[2F.j=r(ZK]YeY[iZ\'Y,L,XUffGB)G-j$`{w5}P?S@0=Jgu1q<S~4:qbt9aBwZ-uwA+YP*x.zT?-(h/A%3F\x7fKO"s"#Urc6OHE}VB8RYJD$IX+QDet9n`J|"D\\oLXv\'pon725p@$N%J6]Q({[A3(ad,1Jyo+aL#h=' == 'a.g>j`bdBjF~{/{)]M|\x7fayqpU_\';Ok9_FTRw>5[^k_6-?*ECO$>bUR-Zxe7\\VqL1Z[N4_^\x7fnx%eT*}ANR@4<*KS:XP\\N/?:gBy&45N\'>]W.&W;7:8/zo|;c\'&XFm1}lx9(vnDH_jtc&l!^8Eu)\x7fdDsSW4W@M&wK.iEfMWbMiPU#^%R,t~<5HI{n:}ug3f!;7y<\x7fO0E\\;i^qIlvxekI,7~c2|C|+h/Vv3<C6o+=CvH"m`k0`)Sr8V?syr"QQ8izAGTPph=2QltIKpGMmVsT0hd*0!\\36L>1)k#9]C~scgb%u!@r!Gzm2m#z$Hdlf[2F.j=r(ZK]YeY[iZ\'Y,L,XUffGB)G-j$`{w5}P?S@0=Jgu1q<S~4:qbt9aBwZ-uwA+YP*x.zT?-(h/A%3F\x7fKO"s"#Urc6OHE}VB8RYJD$IX+QDet9n`J|"D\\oLXv\'pon725p@$N%J6]Q({[A3(ad,1Jyo+aL#h=\n', "%s lexer roundtrip failed: %r != %r" % \
        (cls.name, 'a.g>j`bdBjF~{/{)]M|\x7fayqpU_\';Ok9_FTRw>5[^k_6-?*ECO$>bUR-Zxe7\\VqL1Z[N4_^\x7fnx%eT*}ANR@4<*KS:XP\\N/?:gBy&45N\'>]W.&W;7:8/zo|;c\'&XFm1}lx9(vnDH_jtc&l!^8Eu)\x7fdDsSW4W@M&wK.iEfMWbMiPU#^%R,t~<5HI{n:}ug3f!;7y<\x7fO0E\\;i^qIlvxekI,7~c2|C|+h/Vv3<C6o+=CvH"m`k0`)Sr8V?syr"QQ8izAGTPph=2QltIKpGMmVsT0hd*0!\\36L>1)k#9]C~scgb%u!@r!Gzm2m#z$Hdlf[2F.j=r(ZK]YeY[iZ\'Y,L,XUffGB)G-j$`{w5}P?S@0=Jgu1q<S~4:qbt9aBwZ-uwA+YP*x.zT?-(h/A%3F\x7fKO"s"#Urc6OHE}VB8RYJD$IX+QDet9n`J|"D\\oLXv\'pon725p@$N%J6]Q({[A3(ad,1Jyo+aL#h=\n', 'a.g>j`bdBjF~{/{)]M|\x7fayqpU_\';Ok9_FTRw>5[^k_6-?*ECO$>bUR-Zxe7\\VqL1Z[N4_^\x7fnx%eT*}ANR@4<*KS:XP\\N/?:gBy&45N\'>]W.&W;7:8/zo|;c\'&XFm1}lx9(vnDH_jtc&l!^8Eu)\x7fdDsSW4W@M&wK.iEfMWbMiPU#^%R,t~<5HI{n:}ug3f!;7y<\x7fO0E\\;i^qIlvxekI,7~c2|C|+h/Vv3<C6o+=CvH"m`k0`)Sr8V?syr"QQ8izAGTPph=2QltIKpGMmVsT0hd*0!\\36L>1)k#9]C~scgb%u!@r!Gzm2m#z$Hdlf[2F.j=r(ZK]YeY[iZ\'Y,L,XUffGB)G-j$`{w5}P?S@0=Jgu1q<S~4:qbt9aBwZ-uwA+YP*x.zT?-(h/A%3F\x7fKO"s"#Urc6OHE}VB8RYJD$IX+QDet9n`J|"D\\oLXv\'pon725p@$N%J6]Q({[A3(ad,1Jyo+aL#h=')
    

======================================================================
FAIL: test_basic_api.test_lexer_classes(<class 'pygments.lexers.templates.Angular2Lexer'>,)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File ".../tests/test_basic_api.py", line 81, in verify
    (cls.name, test_content, txt)
AssertionError: Angular2 lexer roundtrip failed: 'a.g>j`bdBjF~{/{)]M|\x7fayqpU_\';Ok9_FTRw>5[^k_6-?*ECO$>bUR-Zxe7\\VqL1Z[N4_^\x7fnx%eT*}ANR@4<*KS:XP\\N/?:gBy&45N\'>]W.&W;7:8/zo|;c\'&XFm1}lx9(vnDH_jtc&l!^8Eu)\x7fdDsSW4W@M&wK.iEfMWbMiPU#^%R,t~<5HI{n:}ug3f!;7y<\x7fO0E\\;i^qIlvxekI,7~c2|C|+h/Vv3<C6o+=CvH"m`k0`)Sr8V?syr"QQ8izAGTPph=2QltIKpGMmVsT0hd*0!\\36L>1)k#9]C~scgb%u!@r!Gzm2m#z$Hdlf[2F.j=r(ZK]YeY[iZ\'Y,L,XUffGB)G-j$`{w5}P?S@0=Jgu1q<S~4:qbt9aBwZ-uwA+YP*x.zT?-(h/A%3F\x7fKO"s"#Urc6OHE}VB8RYJD$IX+QDet9n`J|"D\\oLXv\'pon725p@$N%J6]Q({[A3(ad,1Jyo+aL#h=\n' != 'a.g>j`bdBjF~{/{)]M|\x7fayqpU_\';Ok9_FTRw>5[^k_6-?*ECO$>bUR-Zxe7\\VqL1Z[N4_^\x7fnx%eT*}ANR@4<*KS:XP\\N/?:gBy&45N\'>]W.&W;7:8/zo|;c\'&XFm1}lx9(vnDH_jtc&l!^8Eu)\x7fdDsSW4W@M&wK.iEfMWbMiPU#^%R,t~<5HI{n:}ug3f!;7y<\x7fO0E\\;i^qIlvxekI,7~c2|C|+h/Vv3<C6o+=CvH"m`k0`)Sr8V?syr"QQ8izAGTPph=2QltIKpGMmVsT0hd*0!\\36L>1)k#9]C~scgb%u!@r!Gzm2m#z$Hdlf[2F.j=r(ZK]YeY[iZ\'Y,L,XUffGB)G-j$`{w5}P?S@0=Jgu1q<S~4:qbt9aBwZ-uwA+YP*x.zT?-(h/A%3F\x7fKO"s"#Urc6OHE}VB8RYJD$IX+QDet9n`J|"D\\oLXv\'pon725p@$N%J6]Q({[A3(ad,1Jyo+aL#h='
>>  assert 'a.g>j`bdBjF~{/{)]M|\x7fayqpU_\';Ok9_FTRw>5[^k_6-?*ECO$>bUR-Zxe7\\VqL1Z[N4_^\x7fnx%eT*}ANR@4<*KS:XP\\N/?:gBy&45N\'>]W.&W;7:8/zo|;c\'&XFm1}lx9(vnDH_jtc&l!^8Eu)\x7fdDsSW4W@M&wK.iEfMWbMiPU#^%R,t~<5HI{n:}ug3f!;7y<\x7fO0E\\;i^qIlvxekI,7~c2|C|+h/Vv3<C6o+=CvH"m`k0`)Sr8V?syr"QQ8izAGTPph=2QltIKpGMmVsT0hd*0!\\36L>1)k#9]C~scgb%u!@r!Gzm2m#z$Hdlf[2F.j=r(ZK]YeY[iZ\'Y,L,XUffGB)G-j$`{w5}P?S@0=Jgu1q<S~4:qbt9aBwZ-uwA+YP*x.zT?-(h/A%3F\x7fKO"s"#Urc6OHE}VB8RYJD$IX+QDet9n`J|"D\\oLXv\'pon725p@$N%J6]Q({[A3(ad,1Jyo+aL#h=' == 'a.g>j`bdBjF~{/{)]M|\x7fayqpU_\';Ok9_FTRw>5[^k_6-?*ECO$>bUR-Zxe7\\VqL1Z[N4_^\x7fnx%eT*}ANR@4<*KS:XP\\N/?:gBy&45N\'>]W.&W;7:8/zo|;c\'&XFm1}lx9(vnDH_jtc&l!^8Eu)\x7fdDsSW4W@M&wK.iEfMWbMiPU#^%R,t~<5HI{n:}ug3f!;7y<\x7fO0E\\;i^qIlvxekI,7~c2|C|+h/Vv3<C6o+=CvH"m`k0`)Sr8V?syr"QQ8izAGTPph=2QltIKpGMmVsT0hd*0!\\36L>1)k#9]C~scgb%u!@r!Gzm2m#z$Hdlf[2F.j=r(ZK]YeY[iZ\'Y,L,XUffGB)G-j$`{w5}P?S@0=Jgu1q<S~4:qbt9aBwZ-uwA+YP*x.zT?-(h/A%3F\x7fKO"s"#Urc6OHE}VB8RYJD$IX+QDet9n`J|"D\\oLXv\'pon725p@$N%J6]Q({[A3(ad,1Jyo+aL#h=\n', "%s lexer roundtrip failed: %r != %r" % \
        (cls.name, 'a.g>j`bdBjF~{/{)]M|\x7fayqpU_\';Ok9_FTRw>5[^k_6-?*ECO$>bUR-Zxe7\\VqL1Z[N4_^\x7fnx%eT*}ANR@4<*KS:XP\\N/?:gBy&45N\'>]W.&W;7:8/zo|;c\'&XFm1}lx9(vnDH_jtc&l!^8Eu)\x7fdDsSW4W@M&wK.iEfMWbMiPU#^%R,t~<5HI{n:}ug3f!;7y<\x7fO0E\\;i^qIlvxekI,7~c2|C|+h/Vv3<C6o+=CvH"m`k0`)Sr8V?syr"QQ8izAGTPph=2QltIKpGMmVsT0hd*0!\\36L>1)k#9]C~scgb%u!@r!Gzm2m#z$Hdlf[2F.j=r(ZK]YeY[iZ\'Y,L,XUffGB)G-j$`{w5}P?S@0=Jgu1q<S~4:qbt9aBwZ-uwA+YP*x.zT?-(h/A%3F\x7fKO"s"#Urc6OHE}VB8RYJD$IX+QDet9n`J|"D\\oLXv\'pon725p@$N%J6]Q({[A3(ad,1Jyo+aL#h=\n', 'a.g>j`bdBjF~{/{)]M|\x7fayqpU_\';Ok9_FTRw>5[^k_6-?*ECO$>bUR-Zxe7\\VqL1Z[N4_^\x7fnx%eT*}ANR@4<*KS:XP\\N/?:gBy&45N\'>]W.&W;7:8/zo|;c\'&XFm1}lx9(vnDH_jtc&l!^8Eu)\x7fdDsSW4W@M&wK.iEfMWbMiPU#^%R,t~<5HI{n:}ug3f!;7y<\x7fO0E\\;i^qIlvxekI,7~c2|C|+h/Vv3<C6o+=CvH"m`k0`)Sr8V?syr"QQ8izAGTPph=2QltIKpGMmVsT0hd*0!\\36L>1)k#9]C~scgb%u!@r!Gzm2m#z$Hdlf[2F.j=r(ZK]YeY[iZ\'Y,L,XUffGB)G-j$`{w5}P?S@0=Jgu1q<S~4:qbt9aBwZ-uwA+YP*x.zT?-(h/A%3F\x7fKO"s"#Urc6OHE}VB8RYJD$IX+QDet9n`J|"D\\oLXv\'pon725p@$N%J6]Q({[A3(ad,1Jyo+aL#h=')
```

**Comment by birkenfeld** [comment]
Can't reproduce this anymore.
